# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmGenericDefaultsEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGenericDefaultsEditor(object):
    def setupUi(self, frmGenericDefaultsEditor):
        frmGenericDefaultsEditor.setObjectName("frmGenericDefaultsEditor")
        frmGenericDefaultsEditor.resize(308, 461)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGenericDefaultsEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmGenericDefaultsEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabDefaults = QtWidgets.QTabWidget(self.centralWidget)
        self.tabDefaults.setObjectName("tabDefaults")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tblGeneric = QtWidgets.QTableWidget(self.tab)
        self.tblGeneric.setObjectName("tblGeneric")
        self.tblGeneric.setColumnCount(0)
        self.tblGeneric.setRowCount(0)
        self.tblGeneric.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tblGeneric, 0, 0, 1, 1)
        self.tabDefaults.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabDefaults.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabDefaults.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabDefaults, 0, 0, 1, 1)
        self.fraNotes = QtWidgets.QFrame(self.centralWidget)
        self.fraNotes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotes.setObjectName("fraNotes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraNotes)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk4all = QtWidgets.QCheckBox(self.fraNotes)
        self.chk4all.setObjectName("chk4all")
        self.horizontalLayout_2.addWidget(self.chk4all)
        self.gridLayout.addWidget(self.fraNotes, 1, 0, 1, 1)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.cmdHelp = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdHelp.setObjectName("cmdHelp")
        self.horizontalLayout.addWidget(self.cmdHelp)
        self.gridLayout.addWidget(self.fraOKCancel, 2, 0, 1, 1)
        frmGenericDefaultsEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGenericDefaultsEditor)
        self.tabDefaults.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmGenericDefaultsEditor)

    def retranslateUi(self, frmGenericDefaultsEditor):
        _translate = QtCore.QCoreApplication.translate
        frmGenericDefaultsEditor.setWindowTitle(_translate("frmGenericDefaultsEditor", "Project Defaults"))
        self.tabDefaults.setTabText(self.tabDefaults.indexOf(self.tab), _translate("frmGenericDefaultsEditor", "Tab 1"))
        self.tabDefaults.setTabText(self.tabDefaults.indexOf(self.tab_2), _translate("frmGenericDefaultsEditor", "Tab 2"))
        self.tabDefaults.setTabText(self.tabDefaults.indexOf(self.tab_3), _translate("frmGenericDefaultsEditor", "Page"))
        self.chk4all.setText(_translate("frmGenericDefaultsEditor", "Save as defaults for all new projects"))
        self.cmdOK.setText(_translate("frmGenericDefaultsEditor", "OK"))
        self.cmdCancel.setText(_translate("frmGenericDefaultsEditor", "Cancel"))
        self.cmdHelp.setText(_translate("frmGenericDefaultsEditor", "Help"))

