# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmRunSimulationDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmRunSimulation(object):
    def setupUi(self, frmRunSimulation):
        frmRunSimulation.setObjectName("frmRunSimulation")
        frmRunSimulation.resize(558, 274)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmRunSimulation.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmRunSimulation)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fraEntire = QtWidgets.QFrame(self.centralWidget)
        self.fraEntire.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraEntire.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraEntire.setObjectName("fraEntire")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fraEntire)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fraRunning = QtWidgets.QFrame(self.fraEntire)
        self.fraRunning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRunning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRunning.setObjectName("fraRunning")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraRunning)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraComputing = QtWidgets.QFrame(self.fraRunning)
        self.fraComputing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraComputing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraComputing.setObjectName("fraComputing")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraComputing)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblIconComputing = QtWidgets.QLabel(self.fraComputing)
        self.lblIconComputing.setText("")
        self.lblIconComputing.setPixmap(QtGui.QPixmap("swmmimages/rain.png"))
        self.lblIconComputing.setObjectName("lblIconComputing")
        self.horizontalLayout_3.addWidget(self.lblIconComputing)
        self.StatusLabel = QtWidgets.QLabel(self.fraComputing)
        self.StatusLabel.setObjectName("StatusLabel")
        self.horizontalLayout_3.addWidget(self.StatusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fraComputing)
        self.progressBar = QtWidgets.QProgressBar(self.fraRunning)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.lblTime = QtWidgets.QLabel(self.fraRunning)
        self.lblTime.setObjectName("lblTime")
        self.verticalLayout.addWidget(self.lblTime)
        self.fraTime = QtWidgets.QFrame(self.fraRunning)
        self.fraTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTime.setObjectName("fraTime")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraTime)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblDays = QtWidgets.QLabel(self.fraTime)
        self.lblDays.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblDays.setObjectName("lblDays")
        self.horizontalLayout_2.addWidget(self.lblDays)
        self.txtDays = QtWidgets.QLabel(self.fraTime)
        self.txtDays.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtDays.setObjectName("txtDays")
        self.horizontalLayout_2.addWidget(self.txtDays)
        self.lblHrsMin = QtWidgets.QLabel(self.fraTime)
        self.lblHrsMin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblHrsMin.setObjectName("lblHrsMin")
        self.horizontalLayout_2.addWidget(self.lblHrsMin)
        self.txtHrsMin = QtWidgets.QLabel(self.fraTime)
        self.txtHrsMin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtHrsMin.setObjectName("txtHrsMin")
        self.horizontalLayout_2.addWidget(self.txtHrsMin)
        self.verticalLayout.addWidget(self.fraTime)
        self.horizontalLayout_5.addWidget(self.fraRunning)
        self.fraFinished = QtWidgets.QFrame(self.fraEntire)
        self.fraFinished.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraFinished.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraFinished.setObjectName("fraFinished")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraFinished)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraSuccessful = QtWidgets.QFrame(self.fraFinished)
        self.fraSuccessful.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraSuccessful.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraSuccessful.setObjectName("fraSuccessful")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fraSuccessful)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblIconSuccessful = QtWidgets.QLabel(self.fraSuccessful)
        self.lblIconSuccessful.setText("")
        self.lblIconSuccessful.setPixmap(QtGui.QPixmap("swmmimages/info.png"))
        self.lblIconSuccessful.setObjectName("lblIconSuccessful")
        self.horizontalLayout_4.addWidget(self.lblIconSuccessful)
        self.lblSuccessful = QtWidgets.QLabel(self.fraSuccessful)
        self.lblSuccessful.setObjectName("lblSuccessful")
        self.horizontalLayout_4.addWidget(self.lblSuccessful)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.fraSuccessful)
        self.gbxContinuity = QtWidgets.QGroupBox(self.fraFinished)
        self.gbxContinuity.setObjectName("gbxContinuity")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxContinuity)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSurface = QtWidgets.QLabel(self.gbxContinuity)
        self.lblSurface.setObjectName("lblSurface")
        self.gridLayout.addWidget(self.lblSurface, 0, 0, 1, 1)
        self.txtSurface = QtWidgets.QLabel(self.gbxContinuity)
        self.txtSurface.setObjectName("txtSurface")
        self.gridLayout.addWidget(self.txtSurface, 0, 1, 1, 1)
        self.lblFlow = QtWidgets.QLabel(self.gbxContinuity)
        self.lblFlow.setObjectName("lblFlow")
        self.gridLayout.addWidget(self.lblFlow, 1, 0, 1, 1)
        self.txtFlow = QtWidgets.QLabel(self.gbxContinuity)
        self.txtFlow.setObjectName("txtFlow")
        self.gridLayout.addWidget(self.txtFlow, 1, 1, 1, 1)
        self.lblQuality = QtWidgets.QLabel(self.gbxContinuity)
        self.lblQuality.setObjectName("lblQuality")
        self.gridLayout.addWidget(self.lblQuality, 2, 0, 1, 1)
        self.txtQuality = QtWidgets.QLabel(self.gbxContinuity)
        self.txtQuality.setObjectName("txtQuality")
        self.gridLayout.addWidget(self.txtQuality, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbxContinuity)
        self.horizontalLayout_5.addWidget(self.fraFinished)
        self.verticalLayout_3.addWidget(self.fraEntire)
        self.fraBottom = QtWidgets.QFrame(self.centralWidget)
        self.fraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBottom.setObjectName("fraBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraBottom)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cmdStop = QtWidgets.QPushButton(self.fraBottom)
        self.cmdStop.setObjectName("cmdStop")
        self.horizontalLayout.addWidget(self.cmdStop)
        self.cmdMinimize = QtWidgets.QPushButton(self.fraBottom)
        self.cmdMinimize.setObjectName("cmdMinimize")
        self.horizontalLayout.addWidget(self.cmdMinimize)
        self.cmdOK = QtWidgets.QPushButton(self.fraBottom)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.fraBottom)
        frmRunSimulation.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmRunSimulation)
        QtCore.QMetaObject.connectSlotsByName(frmRunSimulation)

    def retranslateUi(self, frmRunSimulation):
        _translate = QtCore.QCoreApplication.translate
        frmRunSimulation.setWindowTitle(_translate("frmRunSimulation", "Run Status"))
        self.StatusLabel.setText(_translate("frmRunSimulation", "Computing ..."))
        self.lblTime.setText(_translate("frmRunSimulation", "Simulated Time:"))
        self.lblDays.setText(_translate("frmRunSimulation", "Days"))
        self.txtDays.setText(_translate("frmRunSimulation", "0"))
        self.lblHrsMin.setText(_translate("frmRunSimulation", "Hrs:Min"))
        self.txtHrsMin.setText(_translate("frmRunSimulation", "0"))
        self.lblSuccessful.setText(_translate("frmRunSimulation", "<html><head/><body><p>Run was Successful.</p></body></html>"))
        self.gbxContinuity.setTitle(_translate("frmRunSimulation", "Continuity Error"))
        self.lblSurface.setText(_translate("frmRunSimulation", "Surface Runoff:"))
        self.txtSurface.setText(_translate("frmRunSimulation", "0.0 %"))
        self.lblFlow.setText(_translate("frmRunSimulation", "Flow Routing:"))
        self.txtFlow.setText(_translate("frmRunSimulation", "0.0 %"))
        self.lblQuality.setText(_translate("frmRunSimulation", "Quality Routing:"))
        self.txtQuality.setText(_translate("frmRunSimulation", "0.0 %"))
        self.cmdStop.setText(_translate("frmRunSimulation", "Stop"))
        self.cmdMinimize.setText(_translate("frmRunSimulation", "Minimize"))
        self.cmdOK.setText(_translate("frmRunSimulation", "OK"))

