# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTranslateCoordinatesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTranslateCoordinatesDesigner(object):
    def setupUi(self, frmTranslateCoordinatesDesigner):
        frmTranslateCoordinatesDesigner.setObjectName("frmTranslateCoordinatesDesigner")
        frmTranslateCoordinatesDesigner.resize(482, 258)
        self.gridLayout_3 = QtWidgets.QGridLayout(frmTranslateCoordinatesDesigner)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gbLL = QtWidgets.QGroupBox(frmTranslateCoordinatesDesigner)
        self.gbLL.setObjectName("gbLL")
        self.gridLayout = QtWidgets.QGridLayout(self.gbLL)
        self.gridLayout.setObjectName("gridLayout")
        self.lblLL_src_x = QtWidgets.QLabel(self.gbLL)
        self.lblLL_src_x.setObjectName("lblLL_src_x")
        self.gridLayout.addWidget(self.lblLL_src_x, 0, 0, 1, 1)
        self.txtLL_src_x = QtWidgets.QLineEdit(self.gbLL)
        self.txtLL_src_x.setObjectName("txtLL_src_x")
        self.gridLayout.addWidget(self.txtLL_src_x, 0, 1, 1, 1)
        self.lblLL_dst_x = QtWidgets.QLabel(self.gbLL)
        self.lblLL_dst_x.setObjectName("lblLL_dst_x")
        self.gridLayout.addWidget(self.lblLL_dst_x, 0, 2, 1, 1)
        self.txtLL_dst_x = QtWidgets.QLineEdit(self.gbLL)
        self.txtLL_dst_x.setObjectName("txtLL_dst_x")
        self.gridLayout.addWidget(self.txtLL_dst_x, 0, 3, 1, 1)
        self.lblLL_src_y = QtWidgets.QLabel(self.gbLL)
        self.lblLL_src_y.setObjectName("lblLL_src_y")
        self.gridLayout.addWidget(self.lblLL_src_y, 1, 0, 1, 1)
        self.txtLL_src_y = QtWidgets.QLineEdit(self.gbLL)
        self.txtLL_src_y.setObjectName("txtLL_src_y")
        self.gridLayout.addWidget(self.txtLL_src_y, 1, 1, 1, 1)
        self.lblLL_dst_y = QtWidgets.QLabel(self.gbLL)
        self.lblLL_dst_y.setObjectName("lblLL_dst_y")
        self.gridLayout.addWidget(self.lblLL_dst_y, 1, 2, 1, 1)
        self.txtLL_dst_y = QtWidgets.QLineEdit(self.gbLL)
        self.txtLL_dst_y.setObjectName("txtLL_dst_y")
        self.gridLayout.addWidget(self.txtLL_dst_y, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.gbLL, 0, 0, 1, 7)
        self.gb_UR = QtWidgets.QGroupBox(frmTranslateCoordinatesDesigner)
        self.gb_UR.setObjectName("gb_UR")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_UR)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblUR_src_x = QtWidgets.QLabel(self.gb_UR)
        self.lblUR_src_x.setObjectName("lblUR_src_x")
        self.gridLayout_2.addWidget(self.lblUR_src_x, 0, 0, 1, 1)
        self.txtUR_src_x = QtWidgets.QLineEdit(self.gb_UR)
        self.txtUR_src_x.setObjectName("txtUR_src_x")
        self.gridLayout_2.addWidget(self.txtUR_src_x, 0, 1, 1, 1)
        self.lblUR_dst_x = QtWidgets.QLabel(self.gb_UR)
        self.lblUR_dst_x.setObjectName("lblUR_dst_x")
        self.gridLayout_2.addWidget(self.lblUR_dst_x, 0, 2, 1, 1)
        self.txtUR_dst_x = QtWidgets.QLineEdit(self.gb_UR)
        self.txtUR_dst_x.setObjectName("txtUR_dst_x")
        self.gridLayout_2.addWidget(self.txtUR_dst_x, 0, 3, 1, 1)
        self.lblUR_src_y = QtWidgets.QLabel(self.gb_UR)
        self.lblUR_src_y.setObjectName("lblUR_src_y")
        self.gridLayout_2.addWidget(self.lblUR_src_y, 1, 0, 1, 1)
        self.txtUR_src_y = QtWidgets.QLineEdit(self.gb_UR)
        self.txtUR_src_y.setObjectName("txtUR_src_y")
        self.gridLayout_2.addWidget(self.txtUR_src_y, 1, 1, 1, 1)
        self.lblUR_dst_y = QtWidgets.QLabel(self.gb_UR)
        self.lblUR_dst_y.setObjectName("lblUR_dst_y")
        self.gridLayout_2.addWidget(self.lblUR_dst_y, 1, 2, 1, 1)
        self.txtUR_dst_y = QtWidgets.QLineEdit(self.gb_UR)
        self.txtUR_dst_y.setObjectName("txtUR_dst_y")
        self.gridLayout_2.addWidget(self.txtUR_dst_y, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.gb_UR, 1, 0, 1, 7)
        self.lblUnit = QtWidgets.QLabel(frmTranslateCoordinatesDesigner)
        self.lblUnit.setObjectName("lblUnit")
        self.gridLayout_3.addWidget(self.lblUnit, 2, 0, 1, 1)
        self.rdoUnitFeet = QtWidgets.QRadioButton(frmTranslateCoordinatesDesigner)
        self.rdoUnitFeet.setObjectName("rdoUnitFeet")
        self.gridLayout_3.addWidget(self.rdoUnitFeet, 2, 1, 1, 2)
        self.rdoUnitMeters = QtWidgets.QRadioButton(frmTranslateCoordinatesDesigner)
        self.rdoUnitMeters.setObjectName("rdoUnitMeters")
        self.gridLayout_3.addWidget(self.rdoUnitMeters, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 4, 1, 1)
        self.btnSelectCRS = QtWidgets.QPushButton(frmTranslateCoordinatesDesigner)
        self.btnSelectCRS.setObjectName("btnSelectCRS")
        self.gridLayout_3.addWidget(self.btnSelectCRS, 2, 5, 1, 2)
        self.chkAutoUpdate = QtWidgets.QCheckBox(frmTranslateCoordinatesDesigner)
        self.chkAutoUpdate.setObjectName("chkAutoUpdate")
        self.gridLayout_3.addWidget(self.chkAutoUpdate, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 2, 1, 2)
        self.btnTranslate = QtWidgets.QPushButton(frmTranslateCoordinatesDesigner)
        self.btnTranslate.setObjectName("btnTranslate")
        self.gridLayout_3.addWidget(self.btnTranslate, 3, 4, 1, 2)
        self.btnCancel = QtWidgets.QPushButton(frmTranslateCoordinatesDesigner)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_3.addWidget(self.btnCancel, 3, 6, 1, 1)

        self.retranslateUi(frmTranslateCoordinatesDesigner)
        QtCore.QMetaObject.connectSlotsByName(frmTranslateCoordinatesDesigner)

    def retranslateUi(self, frmTranslateCoordinatesDesigner):
        _translate = QtCore.QCoreApplication.translate
        frmTranslateCoordinatesDesigner.setWindowTitle(_translate("frmTranslateCoordinatesDesigner", "Translate Model Coordinates"))
        self.gbLL.setTitle(_translate("frmTranslateCoordinatesDesigner", "A point selected in the LOWER LEFT corner: specify current and destination coordinates"))
        self.lblLL_src_x.setText(_translate("frmTranslateCoordinatesDesigner", "Current x-coordinate"))
        self.lblLL_dst_x.setText(_translate("frmTranslateCoordinatesDesigner", "Destination x-coordinate"))
        self.lblLL_src_y.setText(_translate("frmTranslateCoordinatesDesigner", "Current y-coordinate"))
        self.lblLL_dst_y.setText(_translate("frmTranslateCoordinatesDesigner", "Destination y-coordinate"))
        self.gb_UR.setTitle(_translate("frmTranslateCoordinatesDesigner", "A point selected in the UPPER RIGHT corner: specify current and destination coordinates"))
        self.lblUR_src_x.setText(_translate("frmTranslateCoordinatesDesigner", "Current x-coordinate"))
        self.lblUR_dst_x.setText(_translate("frmTranslateCoordinatesDesigner", "Destination x-coordinate"))
        self.lblUR_src_y.setText(_translate("frmTranslateCoordinatesDesigner", "Current y-coordinate"))
        self.lblUR_dst_y.setText(_translate("frmTranslateCoordinatesDesigner", "Destination y-coordinate"))
        self.lblUnit.setText(_translate("frmTranslateCoordinatesDesigner", "Destination Coordinate Unit:"))
        self.rdoUnitFeet.setText(_translate("frmTranslateCoordinatesDesigner", "Feet"))
        self.rdoUnitMeters.setText(_translate("frmTranslateCoordinatesDesigner", "Meters"))
        self.btnSelectCRS.setText(_translate("frmTranslateCoordinatesDesigner", "Set Destination CRS"))
        self.chkAutoUpdate.setText(_translate("frmTranslateCoordinatesDesigner", "Re-calculate length and area"))
        self.btnTranslate.setText(_translate("frmTranslateCoordinatesDesigner", "Translate Coordinates"))
        self.btnCancel.setText(_translate("frmTranslateCoordinatesDesigner", "Cancel"))

