from PyQt5 import QtCore, QtGui, QtWidgets


class TextPlusButton(QtWidgets.QFrame):
    def __init__(self, parent):
        QtWidgets.QFrame.__init__(self, parent)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # self.setFont(font)
        # self.centralWidget = QtWidgets.QWidget(frmTextPlus)
        # self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        # self.frame = QtWidgets.QFrame(self.centralWidget)
        # self.frame.setGeometry(QtCore.QRect(40, 50, 189, 22))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        # size_policy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(size_policy)
        self.setMinimumSize(QtCore.QSize(50, 22))
        self.setMaximumSize(QtCore.QSize(16777215, 1010))
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setObjectName("TextPlusButton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textbox = QtWidgets.QLineEdit(self)
        self.textbox.setObjectName("textbox")
        self.horizontalLayout.addWidget(self.textbox)
        self.button = QtWidgets.QPushButton(self)
        button_size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        button_size_policy.setHorizontalStretch(0)
        button_size_policy.setVerticalStretch(0)
        # button_size_policy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(button_size_policy)
        self.button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button.setObjectName("button")
        self.button.setText("...")
        self.horizontalLayout.addWidget(self.button)

