# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmCalibrationDataDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmCalibrationData(object):
    def setupUi(self, frmCalibrationData):
        frmCalibrationData.setObjectName("frmCalibrationData")
        frmCalibrationData.resize(541, 477)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmCalibrationData.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmCalibrationData)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(75)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmCalibrationData.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmCalibrationData)
        QtCore.QMetaObject.connectSlotsByName(frmCalibrationData)

    def retranslateUi(self, frmCalibrationData):
        _translate = QtCore.QCoreApplication.translate
        frmCalibrationData.setWindowTitle(_translate("frmCalibrationData", "SWMM Calibration Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("frmCalibrationData", "Subcatchment Runoff"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("frmCalibrationData", "Subcatchment Washoff"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("frmCalibrationData", "Node Water Depth"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("frmCalibrationData", "Link Flow Rate"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("frmCalibrationData", "Node Water Quality"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("frmCalibrationData", "Node Lateral Inflow"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("frmCalibrationData", "Node Flooding"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("frmCalibrationData", "Groundwater Flow"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("frmCalibrationData", "Groundwater Elevation"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("frmCalibrationData", "Snow Pack Depth"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("frmCalibrationData", "Link Flow Depth"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("frmCalibrationData", "Link Flow Velocity"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("frmCalibrationData", "Name of Calibration File"))
        self.toolButton.setText(_translate("frmCalibrationData", "..."))
        self.cmdOK.setText(_translate("frmCalibrationData", "OK"))
        self.cmdCancel.setText(_translate("frmCalibrationData", "Cancel"))

