# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmClimatologyDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmClimatology(object):
    def setupUi(self, frmClimatology):
        frmClimatology.setObjectName("frmClimatology")
        frmClimatology.resize(618, 417)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmClimatology.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmClimatology)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraTop)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabClimate = QtWidgets.QTabWidget(self.fraTop)
        self.tabClimate.setObjectName("tabClimate")
        self.Temperature = QtWidgets.QWidget()
        self.Temperature.setObjectName("Temperature")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Temperature)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fraNoData = QtWidgets.QFrame(self.Temperature)
        self.fraNoData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNoData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNoData.setObjectName("fraNoData")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraNoData)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblSource = QtWidgets.QLabel(self.fraNoData)
        self.lblSource.setObjectName("lblSource")
        self.verticalLayout_2.addWidget(self.lblSource)
        self.rbnNoData = QtWidgets.QRadioButton(self.fraNoData)
        self.rbnNoData.setObjectName("rbnNoData")
        self.verticalLayout_2.addWidget(self.rbnNoData)
        self.gridLayout_5.addWidget(self.fraNoData, 1, 0, 1, 1)
        self.fraTimeseries = QtWidgets.QFrame(self.Temperature)
        self.fraTimeseries.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTimeseries.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTimeseries.setObjectName("fraTimeseries")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraTimeseries)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbnTimeseries = QtWidgets.QRadioButton(self.fraTimeseries)
        self.rbnTimeseries.setObjectName("rbnTimeseries")
        self.horizontalLayout_2.addWidget(self.rbnTimeseries)
        self.cboTimeSeries = QtWidgets.QComboBox(self.fraTimeseries)
        self.cboTimeSeries.setObjectName("cboTimeSeries")
        self.horizontalLayout_2.addWidget(self.cboTimeSeries)
        self.btnTimeSeries = QtWidgets.QToolButton(self.fraTimeseries)
        self.btnTimeSeries.setObjectName("btnTimeSeries")
        self.horizontalLayout_2.addWidget(self.btnTimeSeries)
        self.gridLayout_5.addWidget(self.fraTimeseries, 2, 0, 1, 1)
        self.fraExternal = QtWidgets.QFrame(self.Temperature)
        self.fraExternal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraExternal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraExternal.setObjectName("fraExternal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraExternal)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtClimate = QtWidgets.QLineEdit(self.fraExternal)
        self.txtClimate.setObjectName("txtClimate")
        self.gridLayout_2.addWidget(self.txtClimate, 2, 0, 1, 2)
        self.btnClimate = QtWidgets.QToolButton(self.fraExternal)
        self.btnClimate.setObjectName("btnClimate")
        self.gridLayout_2.addWidget(self.btnClimate, 2, 2, 1, 1)
        self.dedStart = QtWidgets.QDateEdit(self.fraExternal)
        self.dedStart.setObjectName("dedStart")
        self.gridLayout_2.addWidget(self.dedStart, 3, 1, 1, 2)
        self.cbxStart = QtWidgets.QCheckBox(self.fraExternal)
        self.cbxStart.setObjectName("cbxStart")
        self.gridLayout_2.addWidget(self.cbxStart, 3, 0, 1, 1)
        self.rbnExternal = QtWidgets.QRadioButton(self.fraExternal)
        self.rbnExternal.setObjectName("rbnExternal")
        self.gridLayout_2.addWidget(self.rbnExternal, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.fraExternal, 3, 0, 1, 1)
        self.tabClimate.addTab(self.Temperature, "")
        self.Evaporation = QtWidgets.QWidget()
        self.Evaporation.setObjectName("Evaporation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Evaporation)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fraEvapTop = QtWidgets.QFrame(self.Evaporation)
        self.fraEvapTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraEvapTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraEvapTop.setObjectName("fraEvapTop")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.fraEvapTop)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lblEvap = QtWidgets.QLabel(self.fraEvapTop)
        self.lblEvap.setObjectName("lblEvap")
        self.gridLayout_10.addWidget(self.lblEvap, 0, 0, 1, 1)
        self.cboEvap = QtWidgets.QComboBox(self.fraEvapTop)
        self.cboEvap.setObjectName("cboEvap")
        self.gridLayout_10.addWidget(self.cboEvap, 0, 1, 1, 1)
        self.lblDaily = QtWidgets.QLabel(self.fraEvapTop)
        self.lblDaily.setObjectName("lblDaily")
        self.gridLayout_10.addWidget(self.lblDaily, 1, 0, 1, 1)
        self.txtDaily = QtWidgets.QLineEdit(self.fraEvapTop)
        self.txtDaily.setObjectName("txtDaily")
        self.gridLayout_10.addWidget(self.txtDaily, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 1, 2, 1, 1)
        self.lblEvapTs = QtWidgets.QLabel(self.fraEvapTop)
        self.lblEvapTs.setObjectName("lblEvapTs")
        self.gridLayout_10.addWidget(self.lblEvapTs, 2, 0, 1, 1)
        self.cboEvapTs = QtWidgets.QComboBox(self.fraEvapTop)
        self.cboEvapTs.setObjectName("cboEvapTs")
        self.gridLayout_10.addWidget(self.cboEvapTs, 2, 1, 1, 1)
        self.btnEvapTS = QtWidgets.QToolButton(self.fraEvapTop)
        self.btnEvapTS.setObjectName("btnEvapTS")
        self.gridLayout_10.addWidget(self.btnEvapTS, 2, 2, 1, 1)
        self.lblEvapMisc = QtWidgets.QLabel(self.fraEvapTop)
        self.lblEvapMisc.setWordWrap(True)
        self.lblEvapMisc.setObjectName("lblEvapMisc")
        self.gridLayout_10.addWidget(self.lblEvapMisc, 3, 0, 1, 3)
        self.tblEvap = QtWidgets.QTableWidget(self.fraEvapTop)
        self.tblEvap.setObjectName("tblEvap")
        self.tblEvap.setColumnCount(12)
        self.tblEvap.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEvap.setHorizontalHeaderItem(11, item)
        self.tblEvap.verticalHeader().setVisible(False)
        self.gridLayout_10.addWidget(self.tblEvap, 4, 0, 1, 3)
        self.gridLayout_3.addWidget(self.fraEvapTop, 0, 0, 1, 1)
        self.lineEvap = QtWidgets.QFrame(self.Evaporation)
        self.lineEvap.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineEvap.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineEvap.setObjectName("lineEvap")
        self.gridLayout_3.addWidget(self.lineEvap, 1, 0, 1, 1)
        self.fraEvapBottom = QtWidgets.QFrame(self.Evaporation)
        self.fraEvapBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraEvapBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraEvapBottom.setObjectName("fraEvapBottom")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fraEvapBottom)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblMonthly = QtWidgets.QLabel(self.fraEvapBottom)
        self.lblMonthly.setObjectName("lblMonthly")
        self.gridLayout_4.addWidget(self.lblMonthly, 0, 0, 1, 1)
        self.cboMonthly = QtWidgets.QComboBox(self.fraEvapBottom)
        self.cboMonthly.setObjectName("cboMonthly")
        self.gridLayout_4.addWidget(self.cboMonthly, 0, 1, 1, 1)
        self.btnPattern = QtWidgets.QToolButton(self.fraEvapBottom)
        self.btnPattern.setObjectName("btnPattern")
        self.gridLayout_4.addWidget(self.btnPattern, 0, 2, 1, 1)
        self.btnDelete = QtWidgets.QToolButton(self.fraEvapBottom)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_4.addWidget(self.btnDelete, 0, 3, 1, 1)
        self.cbxDry = QtWidgets.QCheckBox(self.fraEvapBottom)
        self.cbxDry.setObjectName("cbxDry")
        self.gridLayout_4.addWidget(self.cbxDry, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.fraEvapBottom, 2, 0, 1, 1)
        self.tabClimate.addTab(self.Evaporation, "")
        self.WindSpeed = QtWidgets.QWidget()
        self.WindSpeed.setObjectName("WindSpeed")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.WindSpeed)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rbnUseClimate = QtWidgets.QRadioButton(self.WindSpeed)
        self.rbnUseClimate.setObjectName("rbnUseClimate")
        self.gridLayout_6.addWidget(self.rbnUseClimate, 0, 0, 1, 1)
        self.rbnMonthly = QtWidgets.QRadioButton(self.WindSpeed)
        self.rbnMonthly.setObjectName("rbnMonthly")
        self.gridLayout_6.addWidget(self.rbnMonthly, 1, 0, 1, 1)
        self.lblMonthlyWind = QtWidgets.QLabel(self.WindSpeed)
        self.lblMonthlyWind.setObjectName("lblMonthlyWind")
        self.gridLayout_6.addWidget(self.lblMonthlyWind, 2, 0, 1, 1)
        self.tblWind = QtWidgets.QTableWidget(self.WindSpeed)
        self.tblWind.setRowCount(1)
        self.tblWind.setColumnCount(12)
        self.tblWind.setObjectName("tblWind")
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWind.setHorizontalHeaderItem(11, item)
        self.tblWind.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.tblWind, 3, 0, 1, 1)
        self.fraWindBot = QtWidgets.QFrame(self.WindSpeed)
        self.fraWindBot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraWindBot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraWindBot.setObjectName("fraWindBot")
        self.gridLayout_6.addWidget(self.fraWindBot, 4, 0, 1, 1)
        self.tabClimate.addTab(self.WindSpeed, "")
        self.SnowMelt = QtWidgets.QWidget()
        self.SnowMelt.setObjectName("SnowMelt")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.SnowMelt)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblSnowDivide = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowDivide.setWordWrap(True)
        self.lblSnowDivide.setObjectName("lblSnowDivide")
        self.gridLayout_7.addWidget(self.lblSnowDivide, 0, 0, 1, 1)
        self.txtSnowDivide = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowDivide.setObjectName("txtSnowDivide")
        self.gridLayout_7.addWidget(self.txtSnowDivide, 0, 1, 1, 1)
        self.lblSnowATI = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowATI.setWordWrap(True)
        self.lblSnowATI.setObjectName("lblSnowATI")
        self.gridLayout_7.addWidget(self.lblSnowATI, 1, 0, 1, 1)
        self.txtSnowATI = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowATI.setObjectName("txtSnowATI")
        self.gridLayout_7.addWidget(self.txtSnowATI, 1, 1, 1, 1)
        self.lblSnowMelt = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowMelt.setWordWrap(True)
        self.lblSnowMelt.setObjectName("lblSnowMelt")
        self.gridLayout_7.addWidget(self.lblSnowMelt, 2, 0, 1, 1)
        self.txtSnowMelt = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowMelt.setObjectName("txtSnowMelt")
        self.gridLayout_7.addWidget(self.txtSnowMelt, 2, 1, 1, 1)
        self.lblSnowElevation = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowElevation.setWordWrap(True)
        self.lblSnowElevation.setObjectName("lblSnowElevation")
        self.gridLayout_7.addWidget(self.lblSnowElevation, 3, 0, 1, 1)
        self.txtSnowElevation = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowElevation.setObjectName("txtSnowElevation")
        self.gridLayout_7.addWidget(self.txtSnowElevation, 3, 1, 1, 1)
        self.lblSnowLatitude = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowLatitude.setWordWrap(True)
        self.lblSnowLatitude.setObjectName("lblSnowLatitude")
        self.gridLayout_7.addWidget(self.lblSnowLatitude, 4, 0, 1, 1)
        self.txtSnowLatitude = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowLatitude.setObjectName("txtSnowLatitude")
        self.gridLayout_7.addWidget(self.txtSnowLatitude, 4, 1, 1, 1)
        self.lblSnowLongitude = QtWidgets.QLabel(self.SnowMelt)
        self.lblSnowLongitude.setWordWrap(True)
        self.lblSnowLongitude.setObjectName("lblSnowLongitude")
        self.gridLayout_7.addWidget(self.lblSnowLongitude, 5, 0, 1, 1)
        self.txtSnowLongitude = QtWidgets.QLineEdit(self.SnowMelt)
        self.txtSnowLongitude.setObjectName("txtSnowLongitude")
        self.gridLayout_7.addWidget(self.txtSnowLongitude, 5, 1, 1, 1)
        self.tabClimate.addTab(self.SnowMelt, "")
        self.ArealDepletion = QtWidgets.QWidget()
        self.ArealDepletion.setObjectName("ArealDepletion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ArealDepletion)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblFraction = QtWidgets.QLabel(self.ArealDepletion)
        self.lblFraction.setObjectName("lblFraction")
        self.verticalLayout_6.addWidget(self.lblFraction)
        self.tblAreal = QtWidgets.QTableWidget(self.ArealDepletion)
        self.tblAreal.setRowCount(10)
        self.tblAreal.setColumnCount(2)
        self.tblAreal.setObjectName("tblAreal")
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAreal.setItem(0, 0, item)
        self.tblAreal.verticalHeader().setHighlightSections(True)
        self.verticalLayout_6.addWidget(self.tblAreal)
        self.frame = QtWidgets.QFrame(self.ArealDepletion)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnPerNat = QtWidgets.QPushButton(self.frame)
        self.btnPerNat.setObjectName("btnPerNat")
        self.gridLayout_8.addWidget(self.btnPerNat, 1, 1, 1, 1)
        self.btnPerNo = QtWidgets.QPushButton(self.frame)
        self.btnPerNo.setObjectName("btnPerNo")
        self.gridLayout_8.addWidget(self.btnPerNo, 0, 1, 1, 1)
        self.btnImpNat = QtWidgets.QPushButton(self.frame)
        self.btnImpNat.setObjectName("btnImpNat")
        self.gridLayout_8.addWidget(self.btnImpNat, 1, 0, 1, 1)
        self.btnImpNo = QtWidgets.QPushButton(self.frame)
        self.btnImpNo.setObjectName("btnImpNo")
        self.gridLayout_8.addWidget(self.btnImpNo, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.frame)
        self.tabClimate.addTab(self.ArealDepletion, "")
        self.Adjustments = QtWidgets.QWidget()
        self.Adjustments.setObjectName("Adjustments")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Adjustments)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblAdjustments = QtWidgets.QTableWidget(self.Adjustments)
        self.tblAdjustments.setObjectName("tblAdjustments")
        self.tblAdjustments.setColumnCount(4)
        self.tblAdjustments.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAdjustments.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tblAdjustments)
        self.frame_2 = QtWidgets.QFrame(self.Adjustments)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4.addWidget(self.frame_2)
        self.fraAdjBottom = QtWidgets.QFrame(self.Adjustments)
        self.fraAdjBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraAdjBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraAdjBottom.setObjectName("fraAdjBottom")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.fraAdjBottom)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lblAdjustments = QtWidgets.QLabel(self.fraAdjBottom)
        self.lblAdjustments.setObjectName("lblAdjustments")
        self.gridLayout_9.addWidget(self.lblAdjustments, 0, 0, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.fraAdjBottom)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_9.addWidget(self.btnClear, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.fraAdjBottom)
        self.tabClimate.addTab(self.Adjustments, "")
        self.verticalLayout.addWidget(self.tabClimate)
        self.verticalLayout_3.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmClimatology.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmClimatology)
        self.tabClimate.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmClimatology)

    def retranslateUi(self, frmClimatology):
        _translate = QtCore.QCoreApplication.translate
        frmClimatology.setWindowTitle(_translate("frmClimatology", "SWMM Climatology"))
        self.lblSource.setText(_translate("frmClimatology", "Source of Temperature Data:"))
        self.rbnNoData.setText(_translate("frmClimatology", "No Data"))
        self.rbnTimeseries.setText(_translate("frmClimatology", "Time Series"))
        self.btnTimeSeries.setText(_translate("frmClimatology", "..."))
        self.btnClimate.setText(_translate("frmClimatology", "..."))
        self.cbxStart.setText(_translate("frmClimatology", "Start Reading File At"))
        self.rbnExternal.setText(_translate("frmClimatology", "Exteral Climate File"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.Temperature), _translate("frmClimatology", "Temperature"))
        self.lblEvap.setText(_translate("frmClimatology", "Source of Evaporation Rates"))
        self.lblDaily.setText(_translate("frmClimatology", "Daily Evaporation (in/day)"))
        self.lblEvapTs.setText(_translate("frmClimatology", "Name of Time Series"))
        self.btnEvapTS.setText(_translate("frmClimatology", "..."))
        self.lblEvapMisc.setText(_translate("frmClimatology", "Pan Coefficients"))
        item = self.tblEvap.verticalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Value"))
        item = self.tblEvap.horizontalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Jan"))
        item = self.tblEvap.horizontalHeaderItem(1)
        item.setText(_translate("frmClimatology", "Feb"))
        item = self.tblEvap.horizontalHeaderItem(2)
        item.setText(_translate("frmClimatology", "Mar"))
        item = self.tblEvap.horizontalHeaderItem(3)
        item.setText(_translate("frmClimatology", "Apr"))
        item = self.tblEvap.horizontalHeaderItem(4)
        item.setText(_translate("frmClimatology", "May"))
        item = self.tblEvap.horizontalHeaderItem(5)
        item.setText(_translate("frmClimatology", "Jun"))
        item = self.tblEvap.horizontalHeaderItem(6)
        item.setText(_translate("frmClimatology", "Jul"))
        item = self.tblEvap.horizontalHeaderItem(7)
        item.setText(_translate("frmClimatology", "Aug"))
        item = self.tblEvap.horizontalHeaderItem(8)
        item.setText(_translate("frmClimatology", "Sep"))
        item = self.tblEvap.horizontalHeaderItem(9)
        item.setText(_translate("frmClimatology", "Oct"))
        item = self.tblEvap.horizontalHeaderItem(10)
        item.setText(_translate("frmClimatology", "Nov"))
        item = self.tblEvap.horizontalHeaderItem(11)
        item.setText(_translate("frmClimatology", "Dec"))
        self.lblMonthly.setText(_translate("frmClimatology", "Monthly Soil Recovery Pattern (Optional)"))
        self.btnPattern.setText(_translate("frmClimatology", "..."))
        self.btnDelete.setText(_translate("frmClimatology", "X"))
        self.cbxDry.setText(_translate("frmClimatology", "Evaporate Only During Dry Periods"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.Evaporation), _translate("frmClimatology", "Evaporation"))
        self.rbnUseClimate.setText(_translate("frmClimatology", "Use Climate File Data (see Temperature page)"))
        self.rbnMonthly.setText(_translate("frmClimatology", "Use Monthly Averages"))
        self.lblMonthlyWind.setText(_translate("frmClimatology", "Monthly Wind Speed (mph)"))
        item = self.tblWind.horizontalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Jan"))
        item = self.tblWind.horizontalHeaderItem(1)
        item.setText(_translate("frmClimatology", "Feb"))
        item = self.tblWind.horizontalHeaderItem(2)
        item.setText(_translate("frmClimatology", "Mar"))
        item = self.tblWind.horizontalHeaderItem(3)
        item.setText(_translate("frmClimatology", "Apr"))
        item = self.tblWind.horizontalHeaderItem(4)
        item.setText(_translate("frmClimatology", "May"))
        item = self.tblWind.horizontalHeaderItem(5)
        item.setText(_translate("frmClimatology", "Jun"))
        item = self.tblWind.horizontalHeaderItem(6)
        item.setText(_translate("frmClimatology", "Jul"))
        item = self.tblWind.horizontalHeaderItem(7)
        item.setText(_translate("frmClimatology", "Aug"))
        item = self.tblWind.horizontalHeaderItem(8)
        item.setText(_translate("frmClimatology", "Sep"))
        item = self.tblWind.horizontalHeaderItem(9)
        item.setText(_translate("frmClimatology", "Oct"))
        item = self.tblWind.horizontalHeaderItem(10)
        item.setText(_translate("frmClimatology", "Nov"))
        item = self.tblWind.horizontalHeaderItem(11)
        item.setText(_translate("frmClimatology", "Dec"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.WindSpeed), _translate("frmClimatology", "Wind Speed"))
        self.lblSnowDivide.setText(_translate("frmClimatology", "Dividing Temperature Between Snow and Rain (degrees F)"))
        self.lblSnowATI.setText(_translate("frmClimatology", "ATI Weight (fraction)"))
        self.lblSnowMelt.setText(_translate("frmClimatology", "Negative Melt Ratio (fraction)"))
        self.lblSnowElevation.setText(_translate("frmClimatology", "Elevation Above MLS (feet)"))
        self.lblSnowLatitude.setText(_translate("frmClimatology", "Latitude (degrees)"))
        self.lblSnowLongitude.setText(_translate("frmClimatology", "Longitude Correciton (+/- minutes)"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.SnowMelt), _translate("frmClimatology", "Snow Melt"))
        self.lblFraction.setText(_translate("frmClimatology", "Fraction of Area Covered by Snow, by Depth Ratio"))
        item = self.tblAreal.verticalHeaderItem(0)
        item.setText(_translate("frmClimatology", "0.0"))
        item = self.tblAreal.verticalHeaderItem(1)
        item.setText(_translate("frmClimatology", "0.1"))
        item = self.tblAreal.verticalHeaderItem(2)
        item.setText(_translate("frmClimatology", "0.2"))
        item = self.tblAreal.verticalHeaderItem(3)
        item.setText(_translate("frmClimatology", "0.3"))
        item = self.tblAreal.verticalHeaderItem(4)
        item.setText(_translate("frmClimatology", "0.4"))
        item = self.tblAreal.verticalHeaderItem(5)
        item.setText(_translate("frmClimatology", "0.5"))
        item = self.tblAreal.verticalHeaderItem(6)
        item.setText(_translate("frmClimatology", "0.6"))
        item = self.tblAreal.verticalHeaderItem(7)
        item.setText(_translate("frmClimatology", "0.7"))
        item = self.tblAreal.verticalHeaderItem(8)
        item.setText(_translate("frmClimatology", "0.8"))
        item = self.tblAreal.verticalHeaderItem(9)
        item.setText(_translate("frmClimatology", "0.9"))
        item = self.tblAreal.horizontalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Impervious"))
        item = self.tblAreal.horizontalHeaderItem(1)
        item.setText(_translate("frmClimatology", "Pervious"))
        __sortingEnabled = self.tblAreal.isSortingEnabled()
        self.tblAreal.setSortingEnabled(False)
        self.tblAreal.setSortingEnabled(__sortingEnabled)
        self.btnPerNat.setText(_translate("frmClimatology", "Natural Area"))
        self.btnPerNo.setText(_translate("frmClimatology", "No Per. Depletion"))
        self.btnImpNat.setText(_translate("frmClimatology", "Natural Area"))
        self.btnImpNo.setText(_translate("frmClimatology", "No Imp. Depletion"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.ArealDepletion), _translate("frmClimatology", "Areal Depletion"))
        item = self.tblAdjustments.verticalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Jan"))
        item = self.tblAdjustments.verticalHeaderItem(1)
        item.setText(_translate("frmClimatology", "Feb"))
        item = self.tblAdjustments.verticalHeaderItem(2)
        item.setText(_translate("frmClimatology", "Mar"))
        item = self.tblAdjustments.verticalHeaderItem(3)
        item.setText(_translate("frmClimatology", "Apr"))
        item = self.tblAdjustments.verticalHeaderItem(4)
        item.setText(_translate("frmClimatology", "May"))
        item = self.tblAdjustments.verticalHeaderItem(5)
        item.setText(_translate("frmClimatology", "Jun"))
        item = self.tblAdjustments.verticalHeaderItem(6)
        item.setText(_translate("frmClimatology", "Jul"))
        item = self.tblAdjustments.verticalHeaderItem(7)
        item.setText(_translate("frmClimatology", "Aug"))
        item = self.tblAdjustments.verticalHeaderItem(8)
        item.setText(_translate("frmClimatology", "Sep"))
        item = self.tblAdjustments.verticalHeaderItem(9)
        item.setText(_translate("frmClimatology", "Oct"))
        item = self.tblAdjustments.verticalHeaderItem(10)
        item.setText(_translate("frmClimatology", "Nov"))
        item = self.tblAdjustments.verticalHeaderItem(11)
        item.setText(_translate("frmClimatology", "Dec"))
        item = self.tblAdjustments.horizontalHeaderItem(0)
        item.setText(_translate("frmClimatology", "Temp"))
        item = self.tblAdjustments.horizontalHeaderItem(1)
        item.setText(_translate("frmClimatology", "Evap"))
        item = self.tblAdjustments.horizontalHeaderItem(2)
        item.setText(_translate("frmClimatology", "Rain"))
        item = self.tblAdjustments.horizontalHeaderItem(3)
        item.setText(_translate("frmClimatology", "Cond"))
        self.lblAdjustments.setText(_translate("frmClimatology", "Temp -- Temperature Adjustment (+- deg F or deg C)\n"
"Evap -- evaporation adjustment (+- in/day or mm/day)\n"
"Rain -- rainfall multiplier\n"
"Cond -- soil conductivity multiplier"))
        self.btnClear.setText(_translate("frmClimatology", "Clear All"))
        self.tabClimate.setTabText(self.tabClimate.indexOf(self.Adjustments), _translate("frmClimatology", "Adjustments"))
        self.cmdOK.setText(_translate("frmClimatology", "OK"))
        self.cmdCancel.setText(_translate("frmClimatology", "Cancel"))

