# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmGroundwaterFlowDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGroundwaterFlow(object):
    def setupUi(self, frmGroundwaterFlow):
        frmGroundwaterFlow.setObjectName("frmGroundwaterFlow")
        frmGroundwaterFlow.resize(680, 464)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmGroundwaterFlow.sizePolicy().hasHeightForWidth())
        frmGroundwaterFlow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGroundwaterFlow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmGroundwaterFlow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fraLeft = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraLeft.sizePolicy().hasHeightForWidth())
        self.fraLeft.setSizePolicy(sizePolicy)
        self.fraLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraLeft.setObjectName("fraLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraLeft)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraTop = QtWidgets.QFrame(self.fraLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraTop.sizePolicy().hasHeightForWidth())
        self.fraTop.setSizePolicy(sizePolicy)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tblGeneric = QtWidgets.QTableWidget(self.fraTop)
        self.tblGeneric.setObjectName("tblGeneric")
        self.tblGeneric.setColumnCount(1)
        self.tblGeneric.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblGeneric.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_4.addWidget(self.tblGeneric)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.fraNotes = QtWidgets.QFrame(self.fraLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraNotes.sizePolicy().hasHeightForWidth())
        self.fraNotes.setSizePolicy(sizePolicy)
        self.fraNotes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotes.setObjectName("fraNotes")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fraNotes)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblNotes = QtWidgets.QLabel(self.fraNotes)
        self.lblNotes.setWordWrap(True)
        self.lblNotes.setObjectName("lblNotes")
        self.horizontalLayout_5.addWidget(self.lblNotes)
        self.verticalLayout_2.addWidget(self.fraNotes)
        self.horizontalLayout_6.addWidget(self.fraLeft)
        self.fraRight = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraRight.sizePolicy().hasHeightForWidth())
        self.fraRight.setSizePolicy(sizePolicy)
        self.fraRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRight.setObjectName("fraRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraRight)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraImage = QtWidgets.QFrame(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraImage.sizePolicy().hasHeightForWidth())
        self.fraImage.setSizePolicy(sizePolicy)
        self.fraImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraImage.setObjectName("fraImage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraImage)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblImage = QtWidgets.QLabel(self.fraImage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap("../swmmimages/gw.png"))
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout.addWidget(self.lblImage)
        self.verticalLayout.addWidget(self.fraImage)
        self.fraText = QtWidgets.QFrame(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraText.sizePolicy().hasHeightForWidth())
        self.fraText.setSizePolicy(sizePolicy)
        self.fraText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraText.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraText.setObjectName("fraText")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraText)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtText = QtWidgets.QTextBrowser(self.fraText)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtText.sizePolicy().hasHeightForWidth())
        self.txtText.setSizePolicy(sizePolicy)
        self.txtText.setMinimumSize(QtCore.QSize(320, 0))
        self.txtText.setObjectName("txtText")
        self.horizontalLayout_3.addWidget(self.txtText)
        self.verticalLayout.addWidget(self.fraText)
        self.fraOKCancel = QtWidgets.QFrame(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraOKCancel.sizePolicy().hasHeightForWidth())
        self.fraOKCancel.setSizePolicy(sizePolicy)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout_2.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout_2.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        self.horizontalLayout_6.addWidget(self.fraRight)
        frmGroundwaterFlow.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGroundwaterFlow)
        QtCore.QMetaObject.connectSlotsByName(frmGroundwaterFlow)

    def retranslateUi(self, frmGroundwaterFlow):
        _translate = QtCore.QCoreApplication.translate
        frmGroundwaterFlow.setWindowTitle(_translate("frmGroundwaterFlow", "SWMM Groundwater Flow Editor"))
        item = self.tblGeneric.horizontalHeaderItem(0)
        item.setText(_translate("frmGroundwaterFlow", "Value"))
        self.lblNotes.setText(_translate("frmGroundwaterFlow", "Explanatory notes"))
        self.txtText.setHtml(_translate("frmGroundwaterFlow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The standard equation for lateral groundwater flow is:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">    QL  =  A1 * (Hgw - Hcb)^B1 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">           - A2 * (Hsw - Hcb)^B2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">           + A3 * Hgw * Hsw</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">where QL has units of cfs/ac (or cms/ha).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The standard equation for deep groundwater flow is:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">    QD  =  LGLR * Hgw / Hgs </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">where LGLR is the aquifer lower GW loss rate (in/hr or</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">mm/hr).</span></p></body></html>"))
        self.cmdOK.setText(_translate("frmGroundwaterFlow", "OK"))
        self.cmdCancel.setText(_translate("frmGroundwaterFlow", "Cancel"))

