# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmGeneralOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGeneralOptions(object):
    def setupUi(self, frmGeneralOptions):
        frmGeneralOptions.setObjectName("frmGeneralOptions")
        frmGeneralOptions.resize(364, 438)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGeneralOptions.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmGeneralOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gbxProcess = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxProcess.setObjectName("gbxProcess")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxProcess)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbxRainfallRunoff = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxRainfallRunoff.setObjectName("cbxRainfallRunoff")
        self.verticalLayout.addWidget(self.cbxRainfallRunoff)
        self.cbxRainfallII = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxRainfallII.setObjectName("cbxRainfallII")
        self.verticalLayout.addWidget(self.cbxRainfallII)
        self.cbxSnowmelt = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxSnowmelt.setObjectName("cbxSnowmelt")
        self.verticalLayout.addWidget(self.cbxSnowmelt)
        self.cbxGroundwater = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxGroundwater.setObjectName("cbxGroundwater")
        self.verticalLayout.addWidget(self.cbxGroundwater)
        self.cbxFlowRouting = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxFlowRouting.setObjectName("cbxFlowRouting")
        self.verticalLayout.addWidget(self.cbxFlowRouting)
        self.cbxWaterQuality = QtWidgets.QCheckBox(self.gbxProcess)
        self.cbxWaterQuality.setObjectName("cbxWaterQuality")
        self.verticalLayout.addWidget(self.cbxWaterQuality)
        self.gridLayout.addWidget(self.gbxProcess, 0, 0, 1, 1)
        self.gbxInfiltration = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxInfiltration.setObjectName("gbxInfiltration")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxInfiltration)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbnHorton = QtWidgets.QRadioButton(self.gbxInfiltration)
        self.rbnHorton.setObjectName("rbnHorton")
        self.verticalLayout_2.addWidget(self.rbnHorton)
        self.rbnModifiedHorton = QtWidgets.QRadioButton(self.gbxInfiltration)
        self.rbnModifiedHorton.setObjectName("rbnModifiedHorton")
        self.verticalLayout_2.addWidget(self.rbnModifiedHorton)
        self.rbnGreenAmpt = QtWidgets.QRadioButton(self.gbxInfiltration)
        self.rbnGreenAmpt.setObjectName("rbnGreenAmpt")
        self.verticalLayout_2.addWidget(self.rbnGreenAmpt)
        self.rbnModifiedGreenAmpt = QtWidgets.QRadioButton(self.gbxInfiltration)
        self.rbnModifiedGreenAmpt.setObjectName("rbnModifiedGreenAmpt")
        self.verticalLayout_2.addWidget(self.rbnModifiedGreenAmpt)
        self.rbnCurveNumber = QtWidgets.QRadioButton(self.gbxInfiltration)
        self.rbnCurveNumber.setObjectName("rbnCurveNumber")
        self.verticalLayout_2.addWidget(self.rbnCurveNumber)
        self.gridLayout.addWidget(self.gbxInfiltration, 0, 1, 1, 1)
        self.gbxRouting = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxRouting.setObjectName("gbxRouting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbxRouting)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbnSteady = QtWidgets.QRadioButton(self.gbxRouting)
        self.rbnSteady.setObjectName("rbnSteady")
        self.verticalLayout_3.addWidget(self.rbnSteady)
        self.rbnKinematic = QtWidgets.QRadioButton(self.gbxRouting)
        self.rbnKinematic.setObjectName("rbnKinematic")
        self.verticalLayout_3.addWidget(self.rbnKinematic)
        self.rbnDynamic = QtWidgets.QRadioButton(self.gbxRouting)
        self.rbnDynamic.setObjectName("rbnDynamic")
        self.verticalLayout_3.addWidget(self.rbnDynamic)
        self.gridLayout.addWidget(self.gbxRouting, 1, 0, 1, 1)
        self.gbxMiscellaneous = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxMiscellaneous.setObjectName("gbxMiscellaneous")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbxMiscellaneous)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbxAllowPonding = QtWidgets.QCheckBox(self.gbxMiscellaneous)
        self.cbxAllowPonding.setObjectName("cbxAllowPonding")
        self.verticalLayout_4.addWidget(self.cbxAllowPonding)
        self.cbxReportControl = QtWidgets.QCheckBox(self.gbxMiscellaneous)
        self.cbxReportControl.setObjectName("cbxReportControl")
        self.verticalLayout_4.addWidget(self.cbxReportControl)
        self.cbxReportInput = QtWidgets.QCheckBox(self.gbxMiscellaneous)
        self.cbxReportInput.setObjectName("cbxReportInput")
        self.verticalLayout_4.addWidget(self.cbxReportInput)
        self.lblMinimum = QtWidgets.QLabel(self.gbxMiscellaneous)
        self.lblMinimum.setObjectName("lblMinimum")
        self.verticalLayout_4.addWidget(self.lblMinimum)
        self.frame_2 = QtWidgets.QFrame(self.gbxMiscellaneous)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtMinimum = QtWidgets.QLineEdit(self.frame_2)
        self.txtMinimum.setMinimumSize(QtCore.QSize(50, 0))
        self.txtMinimum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txtMinimum.setObjectName("txtMinimum")
        self.horizontalLayout_2.addWidget(self.txtMinimum)
        self.lblPercent = QtWidgets.QLabel(self.frame_2)
        self.lblPercent.setObjectName("lblPercent")
        self.horizontalLayout_2.addWidget(self.lblPercent)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.gbxMiscellaneous, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(161, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.frame)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.frame)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 2)
        frmGeneralOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGeneralOptions)
        QtCore.QMetaObject.connectSlotsByName(frmGeneralOptions)
        frmGeneralOptions.setTabOrder(self.cbxRainfallRunoff, self.cbxRainfallII)
        frmGeneralOptions.setTabOrder(self.cbxRainfallII, self.cbxSnowmelt)
        frmGeneralOptions.setTabOrder(self.cbxSnowmelt, self.cbxGroundwater)
        frmGeneralOptions.setTabOrder(self.cbxGroundwater, self.cbxFlowRouting)
        frmGeneralOptions.setTabOrder(self.cbxFlowRouting, self.cbxWaterQuality)
        frmGeneralOptions.setTabOrder(self.cbxWaterQuality, self.rbnSteady)
        frmGeneralOptions.setTabOrder(self.rbnSteady, self.rbnKinematic)
        frmGeneralOptions.setTabOrder(self.rbnKinematic, self.rbnDynamic)
        frmGeneralOptions.setTabOrder(self.rbnDynamic, self.rbnHorton)
        frmGeneralOptions.setTabOrder(self.rbnHorton, self.rbnModifiedHorton)
        frmGeneralOptions.setTabOrder(self.rbnModifiedHorton, self.rbnGreenAmpt)
        frmGeneralOptions.setTabOrder(self.rbnGreenAmpt, self.rbnModifiedGreenAmpt)
        frmGeneralOptions.setTabOrder(self.rbnModifiedGreenAmpt, self.rbnCurveNumber)
        frmGeneralOptions.setTabOrder(self.rbnCurveNumber, self.cbxAllowPonding)
        frmGeneralOptions.setTabOrder(self.cbxAllowPonding, self.cbxReportControl)
        frmGeneralOptions.setTabOrder(self.cbxReportControl, self.cbxReportInput)
        frmGeneralOptions.setTabOrder(self.cbxReportInput, self.txtMinimum)
        frmGeneralOptions.setTabOrder(self.txtMinimum, self.cmdOK)
        frmGeneralOptions.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmGeneralOptions):
        _translate = QtCore.QCoreApplication.translate
        frmGeneralOptions.setWindowTitle(_translate("frmGeneralOptions", "SWMM General Options"))
        self.gbxProcess.setTitle(_translate("frmGeneralOptions", "Process Models"))
        self.cbxRainfallRunoff.setText(_translate("frmGeneralOptions", "Rainfall/Runoff"))
        self.cbxRainfallII.setText(_translate("frmGeneralOptions", "Rainfall Dependent I/I"))
        self.cbxSnowmelt.setText(_translate("frmGeneralOptions", "Snow Melt"))
        self.cbxGroundwater.setText(_translate("frmGeneralOptions", "Groundwater"))
        self.cbxFlowRouting.setText(_translate("frmGeneralOptions", "Flow Routing"))
        self.cbxWaterQuality.setText(_translate("frmGeneralOptions", "Water Quality"))
        self.gbxInfiltration.setTitle(_translate("frmGeneralOptions", "Infiltration Model"))
        self.rbnHorton.setText(_translate("frmGeneralOptions", "Horton"))
        self.rbnModifiedHorton.setText(_translate("frmGeneralOptions", "Modified Horton"))
        self.rbnGreenAmpt.setText(_translate("frmGeneralOptions", "Green-Ampt"))
        self.rbnModifiedGreenAmpt.setText(_translate("frmGeneralOptions", "Modified Green-Ampt"))
        self.rbnCurveNumber.setText(_translate("frmGeneralOptions", "Curve Number"))
        self.gbxRouting.setTitle(_translate("frmGeneralOptions", "Routing Model"))
        self.rbnSteady.setText(_translate("frmGeneralOptions", "Steady Flow"))
        self.rbnKinematic.setText(_translate("frmGeneralOptions", "Kinematic Wave"))
        self.rbnDynamic.setText(_translate("frmGeneralOptions", "Dynamic Wave"))
        self.gbxMiscellaneous.setTitle(_translate("frmGeneralOptions", "Miscellaneous"))
        self.cbxAllowPonding.setText(_translate("frmGeneralOptions", "Allow Ponding"))
        self.cbxReportControl.setText(_translate("frmGeneralOptions", "Report Control Actions"))
        self.cbxReportInput.setText(_translate("frmGeneralOptions", "Report Input Summary"))
        self.lblMinimum.setText(_translate("frmGeneralOptions", "Minimum Conduit Slope"))
        self.lblPercent.setText(_translate("frmGeneralOptions", "(%)"))
        self.cmdOK.setText(_translate("frmGeneralOptions", "OK"))
        self.cmdCancel.setText(_translate("frmGeneralOptions", "Cancel"))

