# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmInterfaceFilesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmInterfaceFiles(object):
    def setupUi(self, frmInterfaceFiles):
        frmInterfaceFiles.setObjectName("frmInterfaceFiles")
        frmInterfaceFiles.resize(452, 342)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmInterfaceFiles.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmInterfaceFiles)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblUseRainfall = QtWidgets.QLabel(self.centralWidget)
        self.lblUseRainfall.setObjectName("lblUseRainfall")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUseRainfall)
        self.txtUseRainfall = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUseRainfall.setObjectName("txtUseRainfall")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUseRainfall)
        self.lblSaveRainfall = QtWidgets.QLabel(self.centralWidget)
        self.lblSaveRainfall.setObjectName("lblSaveRainfall")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblSaveRainfall)
        self.txtSaveRainfall = QtWidgets.QLineEdit(self.centralWidget)
        self.txtSaveRainfall.setObjectName("txtSaveRainfall")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtSaveRainfall)
        self.lblUseRunoff = QtWidgets.QLabel(self.centralWidget)
        self.lblUseRunoff.setObjectName("lblUseRunoff")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblUseRunoff)
        self.txtUseRunoff = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUseRunoff.setObjectName("txtUseRunoff")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtUseRunoff)
        self.lblSaveRunoff = QtWidgets.QLabel(self.centralWidget)
        self.lblSaveRunoff.setObjectName("lblSaveRunoff")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblSaveRunoff)
        self.txtSaveRunoff = QtWidgets.QLineEdit(self.centralWidget)
        self.txtSaveRunoff.setObjectName("txtSaveRunoff")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtSaveRunoff)
        self.lblUseHotstart = QtWidgets.QLabel(self.centralWidget)
        self.lblUseHotstart.setObjectName("lblUseHotstart")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblUseHotstart)
        self.txtUseHotstart = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUseHotstart.setObjectName("txtUseHotstart")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtUseHotstart)
        self.lblSaveHotstart = QtWidgets.QLabel(self.centralWidget)
        self.lblSaveHotstart.setObjectName("lblSaveHotstart")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblSaveHotstart)
        self.txtSaveHotstart = QtWidgets.QLineEdit(self.centralWidget)
        self.txtSaveHotstart.setObjectName("txtSaveHotstart")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtSaveHotstart)
        self.lblUseRDII = QtWidgets.QLabel(self.centralWidget)
        self.lblUseRDII.setObjectName("lblUseRDII")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblUseRDII)
        self.txtUseRDII = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUseRDII.setObjectName("txtUseRDII")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtUseRDII)
        self.lblSaveRDII = QtWidgets.QLabel(self.centralWidget)
        self.lblSaveRDII.setObjectName("lblSaveRDII")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblSaveRDII)
        self.txtSaveRDII = QtWidgets.QLineEdit(self.centralWidget)
        self.txtSaveRDII.setObjectName("txtSaveRDII")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtSaveRDII)
        self.lblUseInflows = QtWidgets.QLabel(self.centralWidget)
        self.lblUseInflows.setObjectName("lblUseInflows")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lblUseInflows)
        self.txtUseInflows = QtWidgets.QLineEdit(self.centralWidget)
        self.txtUseInflows.setObjectName("txtUseInflows")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtUseInflows)
        self.lblSaveOutflows = QtWidgets.QLabel(self.centralWidget)
        self.lblSaveOutflows.setObjectName("lblSaveOutflows")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lblSaveOutflows)
        self.txtSaveOutflows = QtWidgets.QLineEdit(self.centralWidget)
        self.txtSaveOutflows.setObjectName("txtSaveOutflows")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.txtSaveOutflows)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(249, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.frame)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.frame)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.frame)
        frmInterfaceFiles.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmInterfaceFiles)
        QtCore.QMetaObject.connectSlotsByName(frmInterfaceFiles)
        frmInterfaceFiles.setTabOrder(self.txtUseRainfall, self.txtSaveRainfall)
        frmInterfaceFiles.setTabOrder(self.txtSaveRainfall, self.txtUseRunoff)
        frmInterfaceFiles.setTabOrder(self.txtUseRunoff, self.txtSaveRunoff)
        frmInterfaceFiles.setTabOrder(self.txtSaveRunoff, self.txtUseHotstart)
        frmInterfaceFiles.setTabOrder(self.txtUseHotstart, self.txtSaveHotstart)
        frmInterfaceFiles.setTabOrder(self.txtSaveHotstart, self.txtUseRDII)
        frmInterfaceFiles.setTabOrder(self.txtUseRDII, self.txtSaveRDII)
        frmInterfaceFiles.setTabOrder(self.txtSaveRDII, self.txtUseInflows)
        frmInterfaceFiles.setTabOrder(self.txtUseInflows, self.txtSaveOutflows)
        frmInterfaceFiles.setTabOrder(self.txtSaveOutflows, self.cmdOK)
        frmInterfaceFiles.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmInterfaceFiles):
        _translate = QtCore.QCoreApplication.translate
        frmInterfaceFiles.setWindowTitle(_translate("frmInterfaceFiles", "SWMM Interface File Options"))
        self.lblUseRainfall.setText(_translate("frmInterfaceFiles", "<html><head/><body><p>Use Rainfall</p></body></html>"))
        self.lblSaveRainfall.setText(_translate("frmInterfaceFiles", "Save Rainfall"))
        self.lblUseRunoff.setText(_translate("frmInterfaceFiles", "Use Runoff"))
        self.lblSaveRunoff.setText(_translate("frmInterfaceFiles", "Save Runoff"))
        self.lblUseHotstart.setText(_translate("frmInterfaceFiles", "Use Hotstart"))
        self.lblSaveHotstart.setText(_translate("frmInterfaceFiles", "Save Hotstart"))
        self.lblUseRDII.setText(_translate("frmInterfaceFiles", "Use RDII"))
        self.lblSaveRDII.setText(_translate("frmInterfaceFiles", "Save RDII"))
        self.lblUseInflows.setText(_translate("frmInterfaceFiles", "Use Inflows"))
        self.lblSaveOutflows.setText(_translate("frmInterfaceFiles", "Save Outflows"))
        self.cmdOK.setText(_translate("frmInterfaceFiles", "OK"))
        self.cmdCancel.setText(_translate("frmInterfaceFiles", "Cancel"))

