# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmInfiltrationDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmInfiltrationEditor(object):
    def setupUi(self, frmInfiltrationEditor):
        frmInfiltrationEditor.setObjectName("frmInfiltrationEditor")
        frmInfiltrationEditor.resize(285, 338)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmInfiltrationEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmInfiltrationEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.formLayout = QtWidgets.QFormLayout(self.fraTop)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblTop = QtWidgets.QLabel(self.fraTop)
        self.lblTop.setObjectName("lblTop")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblTop)
        self.cboInfilModel = QtWidgets.QComboBox(self.fraTop)
        self.cboInfilModel.setObjectName("cboInfilModel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cboInfilModel)
        self.tblGeneric = QtWidgets.QTableWidget(self.fraTop)
        self.tblGeneric.setObjectName("tblGeneric")
        self.tblGeneric.setColumnCount(1)
        self.tblGeneric.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblGeneric.setHorizontalHeaderItem(0, item)
        self.tblGeneric.horizontalHeader().setStretchLastSection(True)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.tblGeneric)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.fraNotes = QtWidgets.QFrame(self.centralWidget)
        self.fraNotes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotes.setObjectName("fraNotes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraNotes)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNotes = QtWidgets.QLabel(self.fraNotes)
        self.lblNotes.setWordWrap(True)
        self.lblNotes.setObjectName("lblNotes")
        self.verticalLayout.addWidget(self.lblNotes)
        self.verticalLayout_2.addWidget(self.fraNotes)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmInfiltrationEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmInfiltrationEditor)
        QtCore.QMetaObject.connectSlotsByName(frmInfiltrationEditor)

    def retranslateUi(self, frmInfiltrationEditor):
        _translate = QtCore.QCoreApplication.translate
        frmInfiltrationEditor.setWindowTitle(_translate("frmInfiltrationEditor", "SWMM Infiltration Editor"))
        self.lblTop.setText(_translate("frmInfiltrationEditor", "<html><head/><body><p>Infiltration Method:  </p></body></html>"))
        item = self.tblGeneric.horizontalHeaderItem(0)
        item.setText(_translate("frmInfiltrationEditor", "Value"))
        self.lblNotes.setText(_translate("frmInfiltrationEditor", "Explanatory notes"))
        self.cmdOK.setText(_translate("frmInfiltrationEditor", "OK"))
        self.cmdCancel.setText(_translate("frmInfiltrationEditor", "Cancel"))

