# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmInflowsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmInflows(object):
    def setupUi(self, frmInflows):
        frmInflows.setObjectName("frmInflows")
        frmInflows.resize(397, 491)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmInflows.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmInflows)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraTop)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabInflows = QtWidgets.QTabWidget(self.fraTop)
        self.tabInflows.setObjectName("tabInflows")
        self.tabDirect = QtWidgets.QWidget()
        self.tabDirect.setObjectName("tabDirect")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabDirect)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblInflow = QtWidgets.QLabel(self.tabDirect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInflow.sizePolicy().hasHeightForWidth())
        self.lblInflow.setSizePolicy(sizePolicy)
        self.lblInflow.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lblInflow.setWordWrap(False)
        self.lblInflow.setObjectName("lblInflow")
        self.verticalLayout_3.addWidget(self.lblInflow)
        self.fraDirect = QtWidgets.QFrame(self.tabDirect)
        self.fraDirect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraDirect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraDirect.setObjectName("fraDirect")
        self.gridLayout = QtWidgets.QGridLayout(self.fraDirect)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblConstituent = QtWidgets.QLabel(self.fraDirect)
        self.lblConstituent.setObjectName("lblConstituent")
        self.gridLayout.addWidget(self.lblConstituent, 0, 0, 1, 1)
        self.cboConstituent = QtWidgets.QComboBox(self.fraDirect)
        self.cboConstituent.setObjectName("cboConstituent")
        self.gridLayout.addWidget(self.cboConstituent, 0, 1, 1, 1)
        self.lblBaseline = QtWidgets.QLabel(self.fraDirect)
        self.lblBaseline.setObjectName("lblBaseline")
        self.gridLayout.addWidget(self.lblBaseline, 1, 0, 1, 1)
        self.txtBaseline = QtWidgets.QLineEdit(self.fraDirect)
        self.txtBaseline.setObjectName("txtBaseline")
        self.gridLayout.addWidget(self.txtBaseline, 1, 1, 1, 1)
        self.btnBaseline = QtWidgets.QToolButton(self.fraDirect)
        self.btnBaseline.setObjectName("btnBaseline")
        self.gridLayout.addWidget(self.btnBaseline, 1, 2, 1, 1)
        self.lblBaselinePattern = QtWidgets.QLabel(self.fraDirect)
        self.lblBaselinePattern.setObjectName("lblBaselinePattern")
        self.gridLayout.addWidget(self.lblBaselinePattern, 2, 0, 1, 1)
        self.cboPattern = QtWidgets.QComboBox(self.fraDirect)
        self.cboPattern.setObjectName("cboPattern")
        self.gridLayout.addWidget(self.cboPattern, 2, 1, 1, 1)
        self.btnPattern = QtWidgets.QToolButton(self.fraDirect)
        self.btnPattern.setObjectName("btnPattern")
        self.gridLayout.addWidget(self.btnPattern, 2, 2, 1, 1)
        self.btnPatternDelete = QtWidgets.QToolButton(self.fraDirect)
        self.btnPatternDelete.setObjectName("btnPatternDelete")
        self.gridLayout.addWidget(self.btnPatternDelete, 2, 3, 1, 1)
        self.lblTimeseries = QtWidgets.QLabel(self.fraDirect)
        self.lblTimeseries.setObjectName("lblTimeseries")
        self.gridLayout.addWidget(self.lblTimeseries, 3, 0, 1, 1)
        self.cboTimeSeries = QtWidgets.QComboBox(self.fraDirect)
        self.cboTimeSeries.setObjectName("cboTimeSeries")
        self.gridLayout.addWidget(self.cboTimeSeries, 3, 1, 1, 1)
        self.btnTimeseries = QtWidgets.QToolButton(self.fraDirect)
        self.btnTimeseries.setObjectName("btnTimeseries")
        self.gridLayout.addWidget(self.btnTimeseries, 3, 2, 1, 1)
        self.btnTimeseriesDelete = QtWidgets.QToolButton(self.fraDirect)
        self.btnTimeseriesDelete.setObjectName("btnTimeseriesDelete")
        self.gridLayout.addWidget(self.btnTimeseriesDelete, 3, 3, 1, 1)
        self.lblScaleFactor = QtWidgets.QLabel(self.fraDirect)
        self.lblScaleFactor.setObjectName("lblScaleFactor")
        self.gridLayout.addWidget(self.lblScaleFactor, 4, 0, 1, 1)
        self.txtScaleFactor = QtWidgets.QLineEdit(self.fraDirect)
        self.txtScaleFactor.setObjectName("txtScaleFactor")
        self.gridLayout.addWidget(self.txtScaleFactor, 4, 1, 1, 1)
        self.lblInflowType = QtWidgets.QLabel(self.fraDirect)
        self.lblInflowType.setObjectName("lblInflowType")
        self.gridLayout.addWidget(self.lblInflowType, 5, 0, 1, 1)
        self.cboInflowType = QtWidgets.QComboBox(self.fraDirect)
        self.cboInflowType.setObjectName("cboInflowType")
        self.gridLayout.addWidget(self.cboInflowType, 5, 1, 1, 1)
        self.lblUnitsFactor = QtWidgets.QLabel(self.fraDirect)
        self.lblUnitsFactor.setObjectName("lblUnitsFactor")
        self.gridLayout.addWidget(self.lblUnitsFactor, 6, 0, 1, 1)
        self.txtUnitsFactor = QtWidgets.QLineEdit(self.fraDirect)
        self.txtUnitsFactor.setObjectName("txtUnitsFactor")
        self.gridLayout.addWidget(self.txtUnitsFactor, 6, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.fraDirect)
        self.tabInflows.addTab(self.tabDirect, "")
        self.tabDry = QtWidgets.QWidget()
        self.tabDry.setObjectName("tabDry")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabDry)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblInflow2 = QtWidgets.QLabel(self.tabDry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInflow2.sizePolicy().hasHeightForWidth())
        self.lblInflow2.setSizePolicy(sizePolicy)
        self.lblInflow2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lblInflow2.setWordWrap(False)
        self.lblInflow2.setObjectName("lblInflow2")
        self.verticalLayout_5.addWidget(self.lblInflow2)
        self.fraDry = QtWidgets.QFrame(self.tabDry)
        self.fraDry.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraDry.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraDry.setObjectName("fraDry")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraDry)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblDryConstituent = QtWidgets.QLabel(self.fraDry)
        self.lblDryConstituent.setObjectName("lblDryConstituent")
        self.gridLayout_2.addWidget(self.lblDryConstituent, 0, 0, 1, 1)
        self.cboDryConstituent = QtWidgets.QComboBox(self.fraDry)
        self.cboDryConstituent.setObjectName("cboDryConstituent")
        self.gridLayout_2.addWidget(self.cboDryConstituent, 0, 1, 1, 1)
        self.lblAverage = QtWidgets.QLabel(self.fraDry)
        self.lblAverage.setObjectName("lblAverage")
        self.gridLayout_2.addWidget(self.lblAverage, 1, 0, 1, 1)
        self.txtAverage = QtWidgets.QLineEdit(self.fraDry)
        self.txtAverage.setObjectName("txtAverage")
        self.gridLayout_2.addWidget(self.txtAverage, 1, 1, 1, 1)
        self.btnAverage = QtWidgets.QToolButton(self.fraDry)
        self.btnAverage.setObjectName("btnAverage")
        self.gridLayout_2.addWidget(self.btnAverage, 1, 3, 1, 1)
        self.lblPatterns = QtWidgets.QLabel(self.fraDry)
        self.lblPatterns.setObjectName("lblPatterns")
        self.gridLayout_2.addWidget(self.lblPatterns, 2, 0, 1, 1)
        self.cboDryPattern1 = QtWidgets.QComboBox(self.fraDry)
        self.cboDryPattern1.setObjectName("cboDryPattern1")
        self.gridLayout_2.addWidget(self.cboDryPattern1, 2, 1, 1, 1)
        self.btnDryPattern1 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern1.setObjectName("btnDryPattern1")
        self.gridLayout_2.addWidget(self.btnDryPattern1, 2, 3, 1, 1)
        self.btnDryPattern5 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern5.setObjectName("btnDryPattern5")
        self.gridLayout_2.addWidget(self.btnDryPattern5, 2, 4, 1, 1)
        self.cboDryPattern2 = QtWidgets.QComboBox(self.fraDry)
        self.cboDryPattern2.setObjectName("cboDryPattern2")
        self.gridLayout_2.addWidget(self.cboDryPattern2, 3, 1, 1, 1)
        self.btnDryPattern3 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern3.setObjectName("btnDryPattern3")
        self.gridLayout_2.addWidget(self.btnDryPattern3, 4, 3, 1, 1)
        self.btnDryPattern7 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern7.setObjectName("btnDryPattern7")
        self.gridLayout_2.addWidget(self.btnDryPattern7, 4, 4, 1, 1)
        self.btnDryPattern6 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern6.setObjectName("btnDryPattern6")
        self.gridLayout_2.addWidget(self.btnDryPattern6, 3, 4, 1, 1)
        self.btnDryPattern2 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern2.setObjectName("btnDryPattern2")
        self.gridLayout_2.addWidget(self.btnDryPattern2, 3, 3, 1, 1)
        self.cboDryPattern3 = QtWidgets.QComboBox(self.fraDry)
        self.cboDryPattern3.setObjectName("cboDryPattern3")
        self.gridLayout_2.addWidget(self.cboDryPattern3, 4, 1, 1, 1)
        self.cboDryPattern4 = QtWidgets.QComboBox(self.fraDry)
        self.cboDryPattern4.setObjectName("cboDryPattern4")
        self.gridLayout_2.addWidget(self.cboDryPattern4, 5, 1, 1, 1)
        self.btnDryPattern4 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern4.setObjectName("btnDryPattern4")
        self.gridLayout_2.addWidget(self.btnDryPattern4, 5, 3, 1, 1)
        self.btnDryPattern8 = QtWidgets.QToolButton(self.fraDry)
        self.btnDryPattern8.setObjectName("btnDryPattern8")
        self.gridLayout_2.addWidget(self.btnDryPattern8, 5, 4, 1, 1)
        self.verticalLayout_5.addWidget(self.fraDry)
        self.tabInflows.addTab(self.tabDry, "")
        self.tabRdii = QtWidgets.QWidget()
        self.tabRdii.setObjectName("tabRdii")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabRdii)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fraUpper = QtWidgets.QFrame(self.tabRdii)
        self.fraUpper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraUpper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraUpper.setObjectName("fraUpper")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fraUpper)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblUnitHydro = QtWidgets.QLabel(self.fraUpper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUnitHydro.sizePolicy().hasHeightForWidth())
        self.lblUnitHydro.setSizePolicy(sizePolicy)
        self.lblUnitHydro.setObjectName("lblUnitHydro")
        self.gridLayout_3.addWidget(self.lblUnitHydro, 0, 0, 1, 2)
        self.cboUnitHydro = QtWidgets.QComboBox(self.fraUpper)
        self.cboUnitHydro.setObjectName("cboUnitHydro")
        self.gridLayout_3.addWidget(self.cboUnitHydro, 1, 0, 1, 1)
        self.btnUnitHydro1 = QtWidgets.QToolButton(self.fraUpper)
        self.btnUnitHydro1.setObjectName("btnUnitHydro1")
        self.gridLayout_3.addWidget(self.btnUnitHydro1, 1, 1, 1, 1)
        self.btnUniHydro2 = QtWidgets.QToolButton(self.fraUpper)
        self.btnUniHydro2.setObjectName("btnUniHydro2")
        self.gridLayout_3.addWidget(self.btnUniHydro2, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.fraUpper)
        self.fraLower = QtWidgets.QFrame(self.tabRdii)
        self.fraLower.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraLower.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraLower.setObjectName("fraLower")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraLower)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSewershed = QtWidgets.QLabel(self.fraLower)
        self.lblSewershed.setWordWrap(True)
        self.lblSewershed.setObjectName("lblSewershed")
        self.horizontalLayout_2.addWidget(self.lblSewershed)
        self.txtSewershed = QtWidgets.QLineEdit(self.fraLower)
        self.txtSewershed.setObjectName("txtSewershed")
        self.horizontalLayout_2.addWidget(self.txtSewershed)
        self.verticalLayout_6.addWidget(self.fraLower)
        self.tabInflows.addTab(self.tabRdii, "")
        self.verticalLayout.addWidget(self.tabInflows)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.gbxNotes = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxNotes.setTitle("")
        self.gbxNotes.setObjectName("gbxNotes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbxNotes)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblNotes = QtWidgets.QLabel(self.gbxNotes)
        self.lblNotes.setWordWrap(True)
        self.lblNotes.setObjectName("lblNotes")
        self.verticalLayout_4.addWidget(self.lblNotes)
        self.verticalLayout_2.addWidget(self.gbxNotes)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmInflows.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmInflows)
        self.tabInflows.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmInflows)

    def retranslateUi(self, frmInflows):
        _translate = QtCore.QCoreApplication.translate
        frmInflows.setWindowTitle(_translate("frmInflows", "SWMM Inflows"))
        self.lblInflow.setText(_translate("frmInflows", "Inflow = (Baseline Value) x (Baseline Pattern) +       \n"
"          (Time Series Value) x (Scale Factor)"))
        self.lblConstituent.setText(_translate("frmInflows", "Constituent"))
        self.lblBaseline.setText(_translate("frmInflows", "Baseline"))
        self.btnBaseline.setText(_translate("frmInflows", "X"))
        self.lblBaselinePattern.setText(_translate("frmInflows", "Baseline Pattern"))
        self.btnPattern.setText(_translate("frmInflows", "..."))
        self.btnPatternDelete.setText(_translate("frmInflows", "X"))
        self.lblTimeseries.setText(_translate("frmInflows", "Time Series"))
        self.btnTimeseries.setText(_translate("frmInflows", "..."))
        self.btnTimeseriesDelete.setText(_translate("frmInflows", "X"))
        self.lblScaleFactor.setText(_translate("frmInflows", "Scale Factor"))
        self.lblInflowType.setText(_translate("frmInflows", "Inflow Type"))
        self.lblUnitsFactor.setText(_translate("frmInflows", "Units Factor"))
        self.tabInflows.setTabText(self.tabInflows.indexOf(self.tabDirect), _translate("frmInflows", "Direct"))
        self.lblInflow2.setText(_translate("frmInflows", "Inflow = (Average Value) x (Pattern 1) x       \n"
"          (Pattern 2) x (Pattern 3) x (Pattern 4)"))
        self.lblDryConstituent.setText(_translate("frmInflows", "Constituent"))
        self.lblAverage.setText(_translate("frmInflows", "Average Value"))
        self.btnAverage.setText(_translate("frmInflows", "X"))
        self.lblPatterns.setText(_translate("frmInflows", "Time Patterns"))
        self.btnDryPattern1.setText(_translate("frmInflows", "..."))
        self.btnDryPattern5.setText(_translate("frmInflows", "X"))
        self.btnDryPattern3.setText(_translate("frmInflows", "..."))
        self.btnDryPattern7.setText(_translate("frmInflows", "X"))
        self.btnDryPattern6.setText(_translate("frmInflows", "X"))
        self.btnDryPattern2.setText(_translate("frmInflows", "..."))
        self.btnDryPattern4.setText(_translate("frmInflows", "..."))
        self.btnDryPattern8.setText(_translate("frmInflows", "X"))
        self.tabInflows.setTabText(self.tabInflows.indexOf(self.tabDry), _translate("frmInflows", "Dry Weather"))
        self.lblUnitHydro.setText(_translate("frmInflows", "Unit Hydrograph Group"))
        self.btnUnitHydro1.setText(_translate("frmInflows", "..."))
        self.btnUniHydro2.setText(_translate("frmInflows", "X"))
        self.lblSewershed.setText(_translate("frmInflows", "Seweshed Area (acres)"))
        self.tabInflows.setTabText(self.tabInflows.indexOf(self.tabRdii), _translate("frmInflows", "RDII"))
        self.lblNotes.setText(_translate("frmInflows", "<html><head/><body><p>If Baseline or Time Series is left blank its value is 0. If Baseline Pattern is left blank its value is 1.0.</p></body></html>"))
        self.cmdOK.setText(_translate("frmInflows", "OK"))
        self.cmdCancel.setText(_translate("frmInflows", "Cancel"))

