# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmLandUsesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmLandUsesEditor(object):
    def setupUi(self, frmLandUsesEditor):
        frmLandUsesEditor.setObjectName("frmLandUsesEditor")
        frmLandUsesEditor.resize(401, 383)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmLandUsesEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmLandUsesEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabLanduse = QtWidgets.QTabWidget(self.centralWidget)
        self.tabLanduse.setObjectName("tabLanduse")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.General)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraGeneral = QtWidgets.QFrame(self.General)
        self.fraGeneral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraGeneral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraGeneral.setObjectName("fraGeneral")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraGeneral)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblGeneral = QtWidgets.QTableWidget(self.fraGeneral)
        self.tblGeneral.setObjectName("tblGeneral")
        self.tblGeneral.setColumnCount(1)
        self.tblGeneral.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblGeneral.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_2.addWidget(self.tblGeneral)
        self.verticalLayout_2.addWidget(self.fraGeneral)
        self.fraNotesGeneral = QtWidgets.QFrame(self.General)
        self.fraNotesGeneral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotesGeneral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotesGeneral.setObjectName("fraNotesGeneral")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraNotesGeneral)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNotesGeneral = QtWidgets.QLabel(self.fraNotesGeneral)
        self.lblNotesGeneral.setWordWrap(True)
        self.lblNotesGeneral.setObjectName("lblNotesGeneral")
        self.verticalLayout.addWidget(self.lblNotesGeneral)
        self.verticalLayout_2.addWidget(self.fraNotesGeneral)
        self.tabLanduse.addTab(self.General, "")
        self.Buildup = QtWidgets.QWidget()
        self.Buildup.setObjectName("Buildup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Buildup)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fraBuildup = QtWidgets.QFrame(self.Buildup)
        self.fraBuildup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBuildup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBuildup.setObjectName("fraBuildup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraBuildup)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tblBuildup = QtWidgets.QTableWidget(self.fraBuildup)
        self.tblBuildup.setObjectName("tblBuildup")
        self.tblBuildup.setColumnCount(1)
        self.tblBuildup.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblBuildup.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.tblBuildup)
        self.verticalLayout_6.addWidget(self.fraBuildup)
        self.fraNotesBuildup = QtWidgets.QFrame(self.Buildup)
        self.fraNotesBuildup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotesBuildup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotesBuildup.setObjectName("fraNotesBuildup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fraNotesBuildup)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblNotesBuildup = QtWidgets.QLabel(self.fraNotesBuildup)
        self.lblNotesBuildup.setWordWrap(True)
        self.lblNotesBuildup.setObjectName("lblNotesBuildup")
        self.verticalLayout_4.addWidget(self.lblNotesBuildup)
        self.verticalLayout_6.addWidget(self.fraNotesBuildup)
        self.tabLanduse.addTab(self.Buildup, "")
        self.Washoff = QtWidgets.QWidget()
        self.Washoff.setObjectName("Washoff")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Washoff)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fraWashoff = QtWidgets.QFrame(self.Washoff)
        self.fraWashoff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraWashoff.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraWashoff.setObjectName("fraWashoff")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fraWashoff)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tblWashoff = QtWidgets.QTableWidget(self.fraWashoff)
        self.tblWashoff.setObjectName("tblWashoff")
        self.tblWashoff.setColumnCount(1)
        self.tblWashoff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblWashoff.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_4.addWidget(self.tblWashoff)
        self.verticalLayout_7.addWidget(self.fraWashoff)
        self.fraNotesWashoff = QtWidgets.QFrame(self.Washoff)
        self.fraNotesWashoff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNotesWashoff.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNotesWashoff.setObjectName("fraNotesWashoff")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fraNotesWashoff)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblNotesWashoff = QtWidgets.QLabel(self.fraNotesWashoff)
        self.lblNotesWashoff.setWordWrap(True)
        self.lblNotesWashoff.setObjectName("lblNotesWashoff")
        self.verticalLayout_5.addWidget(self.lblNotesWashoff)
        self.verticalLayout_7.addWidget(self.fraNotesWashoff)
        self.tabLanduse.addTab(self.Washoff, "")
        self.verticalLayout_3.addWidget(self.tabLanduse)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmLandUsesEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmLandUsesEditor)
        self.tabLanduse.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmLandUsesEditor)

    def retranslateUi(self, frmLandUsesEditor):
        _translate = QtCore.QCoreApplication.translate
        frmLandUsesEditor.setWindowTitle(_translate("frmLandUsesEditor", "SWMM Land Use Editor"))
        item = self.tblGeneral.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value"))
        self.lblNotesGeneral.setText(_translate("frmLandUsesEditor", "Explanatory notes"))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.General), _translate("frmLandUsesEditor", "General"))
        item = self.tblBuildup.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value"))
        self.lblNotesBuildup.setText(_translate("frmLandUsesEditor", "Explanatory notes"))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.Buildup), _translate("frmLandUsesEditor", "Buildup"))
        item = self.tblWashoff.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value"))
        self.lblNotesWashoff.setText(_translate("frmLandUsesEditor", "Explanatory notes"))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.Washoff), _translate("frmLandUsesEditor", "Washoff"))
        self.cmdOK.setText(_translate("frmLandUsesEditor", "OK"))
        self.cmdCancel.setText(_translate("frmLandUsesEditor", "Cancel"))

