# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMapBackdropOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMapBackdropOptions(object):
    def setupUi(self, frmMapBackdropOptions):
        frmMapBackdropOptions.setObjectName("frmMapBackdropOptions")
        frmMapBackdropOptions.resize(516, 464)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMapBackdropOptions.setFont(font)
        frmMapBackdropOptions.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralWidget = QtWidgets.QWidget(frmMapBackdropOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxMap = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxMap.setObjectName("gbxMap")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbxMap)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gbxLLMap = QtWidgets.QGroupBox(self.gbxMap)
        self.gbxLLMap.setObjectName("gbxLLMap")
        self.formLayout_4 = QtWidgets.QFormLayout(self.gbxLLMap)
        self.formLayout_4.setContentsMargins(11, 11, 11, 11)
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblLLX = QtWidgets.QLabel(self.gbxLLMap)
        self.lblLLX.setObjectName("lblLLX")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblLLX)
        self.txtLLXMap = QtWidgets.QLineEdit(self.gbxLLMap)
        self.txtLLXMap.setObjectName("txtLLXMap")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLLXMap)
        self.lblLLY = QtWidgets.QLabel(self.gbxLLMap)
        self.lblLLY.setObjectName("lblLLY")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblLLY)
        self.txtLLYMap = QtWidgets.QLineEdit(self.gbxLLMap)
        self.txtLLYMap.setObjectName("txtLLYMap")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtLLYMap)
        self.horizontalLayout_3.addWidget(self.gbxLLMap)
        self.gbxURMap = QtWidgets.QGroupBox(self.gbxMap)
        self.gbxURMap.setObjectName("gbxURMap")
        self.formLayout_5 = QtWidgets.QFormLayout(self.gbxURMap)
        self.formLayout_5.setContentsMargins(11, 11, 11, 11)
        self.formLayout_5.setSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lblURX = QtWidgets.QLabel(self.gbxURMap)
        self.lblURX.setObjectName("lblURX")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblURX)
        self.txtURXMap = QtWidgets.QLineEdit(self.gbxURMap)
        self.txtURXMap.setObjectName("txtURXMap")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtURXMap)
        self.lblURY = QtWidgets.QLabel(self.gbxURMap)
        self.lblURY.setObjectName("lblURY")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblURY)
        self.txtURYMap = QtWidgets.QLineEdit(self.gbxURMap)
        self.txtURYMap.setObjectName("txtURYMap")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtURYMap)
        self.horizontalLayout_3.addWidget(self.gbxURMap)
        self.verticalLayout.addWidget(self.gbxMap)
        self.gbxMapUnits = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxMapUnits.setObjectName("gbxMapUnits")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbxMapUnits)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbnFeet = QtWidgets.QRadioButton(self.gbxMapUnits)
        self.rbnFeet.setObjectName("rbnFeet")
        self.horizontalLayout_2.addWidget(self.rbnFeet)
        self.rbnMeters = QtWidgets.QRadioButton(self.gbxMapUnits)
        self.rbnMeters.setObjectName("rbnMeters")
        self.horizontalLayout_2.addWidget(self.rbnMeters)
        self.rbnDegrees = QtWidgets.QRadioButton(self.gbxMapUnits)
        self.rbnDegrees.setObjectName("rbnDegrees")
        self.horizontalLayout_2.addWidget(self.rbnDegrees)
        self.rbnNone = QtWidgets.QRadioButton(self.gbxMapUnits)
        self.rbnNone.setObjectName("rbnNone")
        self.horizontalLayout_2.addWidget(self.rbnNone)
        self.verticalLayout.addWidget(self.gbxMapUnits)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblBackdrop = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBackdrop.setFont(font)
        self.lblBackdrop.setObjectName("lblBackdrop")
        self.horizontalLayout_4.addWidget(self.lblBackdrop)
        self.txtBackdropFile = QtWidgets.QLineEdit(self.frame)
        self.txtBackdropFile.setObjectName("txtBackdropFile")
        self.horizontalLayout_4.addWidget(self.txtBackdropFile)
        self.verticalLayout.addWidget(self.frame)
        self.gbxBackdrop = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxBackdrop.setObjectName("gbxBackdrop")
        self.formLayout_3 = QtWidgets.QFormLayout(self.gbxBackdrop)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(11, 11, 11, 11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gbBkDim = QtWidgets.QGroupBox(self.gbxBackdrop)
        self.gbBkDim.setObjectName("gbBkDim")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbBkDim)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbxLLBack = QtWidgets.QGroupBox(self.gbBkDim)
        self.gbxLLBack.setObjectName("gbxLLBack")
        self.formLayout = QtWidgets.QFormLayout(self.gbxLLBack)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblLLXBack = QtWidgets.QLabel(self.gbxLLBack)
        self.lblLLXBack.setObjectName("lblLLXBack")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblLLXBack)
        self.txtLLXBack = QtWidgets.QLineEdit(self.gbxLLBack)
        self.txtLLXBack.setObjectName("txtLLXBack")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLLXBack)
        self.lblLLYBack = QtWidgets.QLabel(self.gbxLLBack)
        self.lblLLYBack.setObjectName("lblLLYBack")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblLLYBack)
        self.txtLLYBack = QtWidgets.QLineEdit(self.gbxLLBack)
        self.txtLLYBack.setObjectName("txtLLYBack")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtLLYBack)
        self.horizontalLayout.addWidget(self.gbxLLBack)
        self.gbxURBack = QtWidgets.QGroupBox(self.gbBkDim)
        self.gbxURBack.setObjectName("gbxURBack")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gbxURBack)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblURXBack = QtWidgets.QLabel(self.gbxURBack)
        self.lblURXBack.setObjectName("lblURXBack")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblURXBack)
        self.txtURXBack = QtWidgets.QLineEdit(self.gbxURBack)
        self.txtURXBack.setObjectName("txtURXBack")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtURXBack)
        self.lblURYBack = QtWidgets.QLabel(self.gbxURBack)
        self.lblURYBack.setObjectName("lblURYBack")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblURYBack)
        self.txtURYBack = QtWidgets.QLineEdit(self.gbxURBack)
        self.txtURYBack.setObjectName("txtURYBack")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtURYBack)
        self.horizontalLayout.addWidget(self.gbxURBack)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.gbBkDim)
        self.verticalLayout.addWidget(self.gbxBackdrop)
        self.fraButtons = QtWidgets.QFrame(self.centralWidget)
        self.fraButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraButtons.setObjectName("fraButtons")
        self.gridLayout = QtWidgets.QGridLayout(self.fraButtons)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.cmdCancel = QtWidgets.QPushButton(self.fraButtons)
        self.cmdCancel.setObjectName("cmdCancel")
        self.gridLayout.addWidget(self.cmdCancel, 0, 2, 1, 1)
        self.cmdOK = QtWidgets.QPushButton(self.fraButtons)
        self.cmdOK.setObjectName("cmdOK")
        self.gridLayout.addWidget(self.cmdOK, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.fraButtons)
        frmMapBackdropOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmMapBackdropOptions)
        QtCore.QMetaObject.connectSlotsByName(frmMapBackdropOptions)
        frmMapBackdropOptions.setTabOrder(self.txtLLXMap, self.txtLLYMap)
        frmMapBackdropOptions.setTabOrder(self.txtLLYMap, self.txtURXMap)
        frmMapBackdropOptions.setTabOrder(self.txtURXMap, self.txtURYMap)
        frmMapBackdropOptions.setTabOrder(self.txtURYMap, self.rbnFeet)
        frmMapBackdropOptions.setTabOrder(self.rbnFeet, self.rbnMeters)
        frmMapBackdropOptions.setTabOrder(self.rbnMeters, self.rbnDegrees)
        frmMapBackdropOptions.setTabOrder(self.rbnDegrees, self.rbnNone)
        frmMapBackdropOptions.setTabOrder(self.rbnNone, self.txtBackdropFile)
        frmMapBackdropOptions.setTabOrder(self.txtBackdropFile, self.txtLLXBack)
        frmMapBackdropOptions.setTabOrder(self.txtLLXBack, self.txtLLYBack)
        frmMapBackdropOptions.setTabOrder(self.txtLLYBack, self.txtURXBack)
        frmMapBackdropOptions.setTabOrder(self.txtURXBack, self.txtURYBack)
        frmMapBackdropOptions.setTabOrder(self.txtURYBack, self.cmdOK)
        frmMapBackdropOptions.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmMapBackdropOptions):
        _translate = QtCore.QCoreApplication.translate
        frmMapBackdropOptions.setWindowTitle(_translate("frmMapBackdropOptions", "SWMM Map/Backdrop Options"))
        self.gbxMap.setTitle(_translate("frmMapBackdropOptions", "Map Dimensions"))
        self.gbxLLMap.setTitle(_translate("frmMapBackdropOptions", "Lower Left"))
        self.lblLLX.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblLLY.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.gbxURMap.setTitle(_translate("frmMapBackdropOptions", "Upper Right"))
        self.lblURX.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblURY.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.gbxMapUnits.setTitle(_translate("frmMapBackdropOptions", "Map Units"))
        self.rbnFeet.setText(_translate("frmMapBackdropOptions", "Feet"))
        self.rbnMeters.setText(_translate("frmMapBackdropOptions", "Meters"))
        self.rbnDegrees.setText(_translate("frmMapBackdropOptions", "Degrees"))
        self.rbnNone.setText(_translate("frmMapBackdropOptions", "None"))
        self.lblBackdrop.setText(_translate("frmMapBackdropOptions", "Backdrop File Name"))
        self.gbxBackdrop.setTitle(_translate("frmMapBackdropOptions", "Backdrop Dimensions"))
        self.gbBkDim.setTitle(_translate("frmMapBackdropOptions", "Dimensions"))
        self.gbxLLBack.setTitle(_translate("frmMapBackdropOptions", "Lower Left"))
        self.lblLLXBack.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblLLYBack.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.gbxURBack.setTitle(_translate("frmMapBackdropOptions", "Upper Right"))
        self.lblURXBack.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblURYBack.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.cmdCancel.setText(_translate("frmMapBackdropOptions", "Cancel"))
        self.cmdOK.setText(_translate("frmMapBackdropOptions", "OK"))

