# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPatternEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPatternEditor(object):
    def setupUi(self, frmPatternEditor):
        frmPatternEditor.setObjectName("frmPatternEditor")
        frmPatternEditor.resize(606, 319)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmPatternEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmPatternEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.gridLayout = QtWidgets.QGridLayout(self.fraParms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblPatternID = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPatternID.setFont(font)
        self.lblPatternID.setObjectName("lblPatternID")
        self.gridLayout.addWidget(self.lblPatternID, 0, 0, 1, 1)
        self.txtPatternID = QtWidgets.QLineEdit(self.fraParms)
        self.txtPatternID.setObjectName("txtPatternID")
        self.gridLayout.addWidget(self.txtPatternID, 0, 1, 1, 1)
        self.lblType = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblType.setFont(font)
        self.lblType.setObjectName("lblType")
        self.gridLayout.addWidget(self.lblType, 0, 2, 1, 1)
        self.cboType = QtWidgets.QComboBox(self.fraParms)
        self.cboType.setObjectName("cboType")
        self.gridLayout.addWidget(self.cboType, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.fraParms)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.txtDescription = QtWidgets.QLineEdit(self.fraParms)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 1, 1, 1, 4)
        self.verticalLayout_2.addWidget(self.fraParms)
        self.fraBottom = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraBottom.sizePolicy().hasHeightForWidth())
        self.fraBottom.setSizePolicy(sizePolicy)
        self.fraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBottom.setObjectName("fraBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraBottom)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblMult = QtWidgets.QTableWidget(self.fraBottom)
        self.tblMult.setRowCount(24)
        self.tblMult.setColumnCount(1)
        self.tblMult.setObjectName("tblMult")
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_2.addWidget(self.tblMult)
        self.fraRight = QtWidgets.QFrame(self.fraBottom)
        self.fraRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRight.setObjectName("fraRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraRight)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.fraOKCancel = QtWidgets.QFrame(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraOKCancel.sizePolicy().hasHeightForWidth())
        self.fraOKCancel.setSizePolicy(sizePolicy)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        self.horizontalLayout_2.addWidget(self.fraRight)
        self.verticalLayout_2.addWidget(self.fraBottom)
        frmPatternEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmPatternEditor)
        QtCore.QMetaObject.connectSlotsByName(frmPatternEditor)

    def retranslateUi(self, frmPatternEditor):
        _translate = QtCore.QCoreApplication.translate
        frmPatternEditor.setWindowTitle(_translate("frmPatternEditor", "SWMM Time Patterns"))
        self.lblPatternID.setText(_translate("frmPatternEditor", "Pattern ID"))
        self.lblType.setText(_translate("frmPatternEditor", "     Type"))
        self.lblDescription.setText(_translate("frmPatternEditor", "<html><head/><body><p>Description</p></body></html>"))
        item = self.tblMult.verticalHeaderItem(0)
        item.setText(_translate("frmPatternEditor", "1"))
        item = self.tblMult.horizontalHeaderItem(0)
        item.setText(_translate("frmPatternEditor", "Multiplier"))
        self.cmdOK.setText(_translate("frmPatternEditor", "OK"))
        self.cmdCancel.setText(_translate("frmPatternEditor", "Cancel"))

