# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSnowPackDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSnowPack(object):
    def setupUi(self, frmSnowPack):
        frmSnowPack.setObjectName("frmSnowPack")
        frmSnowPack.resize(562, 496)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmSnowPack.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmSnowPack)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSnow = QtWidgets.QLabel(self.fraTop)
        self.lblSnow.setObjectName("lblSnow")
        self.horizontalLayout_2.addWidget(self.lblSnow)
        self.txtSnow = QtWidgets.QLineEdit(self.fraTop)
        self.txtSnow.setObjectName("txtSnow")
        self.horizontalLayout_2.addWidget(self.txtSnow)
        self.verticalLayout_3.addWidget(self.fraTop)
        self.fraMiddle = QtWidgets.QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMiddle.setObjectName("fraMiddle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraMiddle)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabSnow = QtWidgets.QTabWidget(self.fraMiddle)
        self.tabSnow.setObjectName("tabSnow")
        self.tabPack = QtWidgets.QWidget()
        self.tabPack.setObjectName("tabPack")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabPack)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblPack = QtWidgets.QTableWidget(self.tabPack)
        self.tblPack.setRowCount(7)
        self.tblPack.setObjectName("tblPack")
        self.tblPack.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(2, item)
        self.tblPack.horizontalHeader().setCascadingSectionResizes(False)
        self.tblPack.horizontalHeader().setDefaultSectionSize(113)
        self.tblPack.horizontalHeader().setStretchLastSection(True)
        self.tblPack.verticalHeader().setDefaultSectionSize(30)
        self.tblPack.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tblPack)
        self.frame = QtWidgets.QFrame(self.tabPack)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblFraction = QtWidgets.QLabel(self.frame)
        self.lblFraction.setObjectName("lblFraction")
        self.horizontalLayout_3.addWidget(self.lblFraction)
        self.txtFraction = QtWidgets.QLineEdit(self.frame)
        self.txtFraction.setObjectName("txtFraction")
        self.horizontalLayout_3.addWidget(self.txtFraction)
        self.verticalLayout.addWidget(self.frame)
        self.tabSnow.addTab(self.tabPack, "")
        self.tabRemoval = QtWidgets.QWidget()
        self.tabRemoval.setObjectName("tabRemoval")
        self.gridLayout = QtWidgets.QGridLayout(self.tabRemoval)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblRemoval1 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval1.setObjectName("lblRemoval1")
        self.gridLayout.addWidget(self.lblRemoval1, 0, 0, 1, 1)
        self.txtRemoval1 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval1.setObjectName("txtRemoval1")
        self.gridLayout.addWidget(self.txtRemoval1, 0, 1, 1, 1)
        self.lblRemoval2 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval2.setObjectName("lblRemoval2")
        self.gridLayout.addWidget(self.lblRemoval2, 1, 0, 1, 1)
        self.txtRemoval2 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval2.setObjectName("txtRemoval2")
        self.gridLayout.addWidget(self.txtRemoval2, 1, 1, 1, 1)
        self.lblRemoval3 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval3.setObjectName("lblRemoval3")
        self.gridLayout.addWidget(self.lblRemoval3, 2, 0, 1, 1)
        self.txtRemoval3 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval3.setObjectName("txtRemoval3")
        self.gridLayout.addWidget(self.txtRemoval3, 2, 1, 1, 1)
        self.lblRemoval4 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval4.setObjectName("lblRemoval4")
        self.gridLayout.addWidget(self.lblRemoval4, 3, 0, 1, 1)
        self.txtRemoval4 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval4.setObjectName("txtRemoval4")
        self.gridLayout.addWidget(self.txtRemoval4, 3, 1, 1, 1)
        self.lblRemoval5 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval5.setObjectName("lblRemoval5")
        self.gridLayout.addWidget(self.lblRemoval5, 4, 0, 1, 1)
        self.txtRemoval5 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval5.setObjectName("txtRemoval5")
        self.gridLayout.addWidget(self.txtRemoval5, 4, 1, 1, 1)
        self.lblRemoval6 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval6.setObjectName("lblRemoval6")
        self.gridLayout.addWidget(self.lblRemoval6, 5, 0, 1, 1)
        self.txtRemoval6 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval6.setObjectName("txtRemoval6")
        self.gridLayout.addWidget(self.txtRemoval6, 5, 1, 1, 1)
        self.lblRemoval7 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval7.setObjectName("lblRemoval7")
        self.gridLayout.addWidget(self.lblRemoval7, 6, 0, 1, 1)
        self.txtRemoval7 = QtWidgets.QLineEdit(self.tabRemoval)
        self.txtRemoval7.setObjectName("txtRemoval7")
        self.gridLayout.addWidget(self.txtRemoval7, 6, 1, 1, 1)
        self.lblRemoval8 = QtWidgets.QLabel(self.tabRemoval)
        self.lblRemoval8.setObjectName("lblRemoval8")
        self.gridLayout.addWidget(self.lblRemoval8, 7, 0, 1, 2)
        self.tabSnow.addTab(self.tabRemoval, "")
        self.verticalLayout_2.addWidget(self.tabSnow)
        self.verticalLayout_3.addWidget(self.fraMiddle)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmSnowPack.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmSnowPack)
        self.tabSnow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmSnowPack)

    def retranslateUi(self, frmSnowPack):
        _translate = QtCore.QCoreApplication.translate
        frmSnowPack.setWindowTitle(_translate("frmSnowPack", "SWMM Snow Pack Editor"))
        self.lblSnow.setText(_translate("frmSnowPack", "Snow Pack Name"))
        item = self.tblPack.verticalHeaderItem(0)
        item.setText(_translate("frmSnowPack", "Min. Melt Coeff. (in/hr/deg F)"))
        item = self.tblPack.verticalHeaderItem(1)
        item.setText(_translate("frmSnowPack", "Max. Melt Coeff. (in/hr/deg F)"))
        item = self.tblPack.verticalHeaderItem(2)
        item.setText(_translate("frmSnowPack", "Base Temperature (deg F)"))
        item = self.tblPack.verticalHeaderItem(3)
        item.setText(_translate("frmSnowPack", "Fraction Free Water Capacity"))
        item = self.tblPack.verticalHeaderItem(4)
        item.setText(_translate("frmSnowPack", "Initial Snow Depth (in)"))
        item = self.tblPack.verticalHeaderItem(5)
        item.setText(_translate("frmSnowPack", "Initial Free Water (in)"))
        item = self.tblPack.verticalHeaderItem(6)
        item.setText(_translate("frmSnowPack", "Depth at 100% Cover (in)"))
        item = self.tblPack.horizontalHeaderItem(0)
        item.setText(_translate("frmSnowPack", "Plowable"))
        item = self.tblPack.horizontalHeaderItem(1)
        item.setText(_translate("frmSnowPack", "Impervious"))
        item = self.tblPack.horizontalHeaderItem(2)
        item.setText(_translate("frmSnowPack", "Pervious"))
        self.lblFraction.setText(_translate("frmSnowPack", "Fraction of Impervious Area that is Plowable:"))
        self.tabSnow.setTabText(self.tabSnow.indexOf(self.tabPack), _translate("frmSnowPack", "Snow Pack Parameters"))
        self.lblRemoval1.setText(_translate("frmSnowPack", "Depth at which snow removal begins (in)"))
        self.lblRemoval2.setText(_translate("frmSnowPack", "Fraction transferred out of the watershed"))
        self.lblRemoval3.setText(_translate("frmSnowPack", "Fraction transferred to the impervious area"))
        self.lblRemoval4.setText(_translate("frmSnowPack", "Fraction transferred to the pervious area"))
        self.lblRemoval5.setText(_translate("frmSnowPack", "Fraction converted into immediate melt"))
        self.lblRemoval6.setText(_translate("frmSnowPack", "Fraction moved to another subcatchment"))
        self.lblRemoval7.setText(_translate("frmSnowPack", "(Subcatchment name)"))
        self.lblRemoval8.setText(_translate("frmSnowPack", "Note: sum of all fractions must be <= 1.0."))
        self.tabSnow.setTabText(self.tabSnow.indexOf(self.tabRemoval), _translate("frmSnowPack", "Snow Removal Parameters"))
        self.cmdOK.setText(_translate("frmSnowPack", "OK"))
        self.cmdCancel.setText(_translate("frmSnowPack", "Cancel"))

