# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmScatterPlotDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmScatterPlot(object):
    def setupUi(self, frmScatterPlot):
        frmScatterPlot.setObjectName("frmScatterPlot")
        frmScatterPlot.resize(379, 478)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmScatterPlot.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmScatterPlot)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxTimePeriods = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxTimePeriods.setTitle("")
        self.gbxTimePeriods.setObjectName("gbxTimePeriods")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxTimePeriods)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.cboStart = QtWidgets.QComboBox(self.gbxTimePeriods)
        self.cboStart.setObjectName("cboStart")
        self.gridLayout.addWidget(self.cboStart, 1, 0, 1, 1)
        self.lblStart = QtWidgets.QLabel(self.gbxTimePeriods)
        self.lblStart.setObjectName("lblStart")
        self.gridLayout.addWidget(self.lblStart, 0, 0, 1, 1)
        self.lblEnd = QtWidgets.QLabel(self.gbxTimePeriods)
        self.lblEnd.setObjectName("lblEnd")
        self.gridLayout.addWidget(self.lblEnd, 0, 1, 1, 1)
        self.cboEnd = QtWidgets.QComboBox(self.gbxTimePeriods)
        self.cboEnd.setObjectName("cboEnd")
        self.gridLayout.addWidget(self.cboEnd, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbxTimePeriods)
        self.fraMid = QtWidgets.QFrame(self.centralWidget)
        self.fraMid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMid.setObjectName("fraMid")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraMid)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gbxX = QtWidgets.QGroupBox(self.fraMid)
        self.gbxX.setObjectName("gbxX")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxX)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblXCat = QtWidgets.QLabel(self.gbxX)
        self.lblXCat.setObjectName("lblXCat")
        self.verticalLayout_2.addWidget(self.lblXCat)
        self.cboXCat = QtWidgets.QComboBox(self.gbxX)
        self.cboXCat.setObjectName("cboXCat")
        self.verticalLayout_2.addWidget(self.cboXCat)
        self.lblObjectX = QtWidgets.QLabel(self.gbxX)
        self.lblObjectX.setObjectName("lblObjectX")
        self.verticalLayout_2.addWidget(self.lblObjectX)
        self.lstX = QtWidgets.QListWidget(self.gbxX)
        self.lstX.setObjectName("lstX")
        self.verticalLayout_2.addWidget(self.lstX)
        self.lblVarX = QtWidgets.QLabel(self.gbxX)
        self.lblVarX.setObjectName("lblVarX")
        self.verticalLayout_2.addWidget(self.lblVarX)
        self.cboVarX = QtWidgets.QComboBox(self.gbxX)
        self.cboVarX.setObjectName("cboVarX")
        self.verticalLayout_2.addWidget(self.cboVarX)
        self.horizontalLayout_3.addWidget(self.gbxX)
        self.gbxY = QtWidgets.QGroupBox(self.fraMid)
        self.gbxY.setObjectName("gbxY")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbxY)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblYCat = QtWidgets.QLabel(self.gbxY)
        self.lblYCat.setObjectName("lblYCat")
        self.verticalLayout_3.addWidget(self.lblYCat)
        self.cboYCat = QtWidgets.QComboBox(self.gbxY)
        self.cboYCat.setObjectName("cboYCat")
        self.verticalLayout_3.addWidget(self.cboYCat)
        self.lblObjectY = QtWidgets.QLabel(self.gbxY)
        self.lblObjectY.setObjectName("lblObjectY")
        self.verticalLayout_3.addWidget(self.lblObjectY)
        self.lstY = QtWidgets.QListWidget(self.gbxY)
        self.lstY.setObjectName("lstY")
        self.verticalLayout_3.addWidget(self.lstY)
        self.lblVarY = QtWidgets.QLabel(self.gbxY)
        self.lblVarY.setObjectName("lblVarY")
        self.verticalLayout_3.addWidget(self.lblVarY)
        self.cboVarY = QtWidgets.QComboBox(self.gbxY)
        self.cboVarY.setObjectName("cboVarY")
        self.verticalLayout_3.addWidget(self.cboVarY)
        self.horizontalLayout_3.addWidget(self.gbxY)
        self.verticalLayout.addWidget(self.fraMid)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmScatterPlot.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmScatterPlot)
        QtCore.QMetaObject.connectSlotsByName(frmScatterPlot)

    def retranslateUi(self, frmScatterPlot):
        _translate = QtCore.QCoreApplication.translate
        frmScatterPlot.setWindowTitle(_translate("frmScatterPlot", "SWMM Scatter Plot Selection"))
        self.lblStart.setText(_translate("frmScatterPlot", "Start Date"))
        self.lblEnd.setText(_translate("frmScatterPlot", "End Date"))
        self.gbxX.setTitle(_translate("frmScatterPlot", "X-Variable"))
        self.lblXCat.setText(_translate("frmScatterPlot", "Object Category"))
        self.lblObjectX.setText(_translate("frmScatterPlot", "Object"))
        self.lblVarX.setText(_translate("frmScatterPlot", "Variable"))
        self.gbxY.setTitle(_translate("frmScatterPlot", "Y-Variable"))
        self.lblYCat.setText(_translate("frmScatterPlot", "Object Category"))
        self.lblObjectY.setText(_translate("frmScatterPlot", "Object"))
        self.lblVarY.setText(_translate("frmScatterPlot", "Variable"))
        self.cmdOK.setText(_translate("frmScatterPlot", "OK"))
        self.cmdCancel.setText(_translate("frmScatterPlot", "Cancel"))

