# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmStatisticsReportSelectionDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmStatisticsReportSelection(object):
    def setupUi(self, frmStatisticsReportSelection):
        frmStatisticsReportSelection.setObjectName("frmStatisticsReportSelection")
        frmStatisticsReportSelection.resize(329, 395)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmStatisticsReportSelection.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmStatisticsReportSelection)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraTop)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cboCategory = QtWidgets.QComboBox(self.fraTop)
        self.cboCategory.setObjectName("cboCategory")
        self.gridLayout_2.addWidget(self.cboCategory, 0, 2, 1, 1)
        self.lblCategory = QtWidgets.QLabel(self.fraTop)
        self.lblCategory.setObjectName("lblCategory")
        self.gridLayout_2.addWidget(self.lblCategory, 0, 1, 1, 1)
        self.lblName = QtWidgets.QLabel(self.fraTop)
        self.lblName.setObjectName("lblName")
        self.gridLayout_2.addWidget(self.lblName, 1, 1, 1, 1)
        self.cboVariable = QtWidgets.QComboBox(self.fraTop)
        self.cboVariable.setObjectName("cboVariable")
        self.gridLayout_2.addWidget(self.cboVariable, 2, 2, 1, 1)
        self.lstName = QtWidgets.QListWidget(self.fraTop)
        self.lstName.setObjectName("lstName")
        self.gridLayout_2.addWidget(self.lstName, 1, 2, 1, 1)
        self.lblVariable = QtWidgets.QLabel(self.fraTop)
        self.lblVariable.setObjectName("lblVariable")
        self.gridLayout_2.addWidget(self.lblVariable, 2, 1, 1, 1)
        self.lblEvent = QtWidgets.QLabel(self.fraTop)
        self.lblEvent.setObjectName("lblEvent")
        self.gridLayout_2.addWidget(self.lblEvent, 3, 1, 1, 1)
        self.cboEvent = QtWidgets.QComboBox(self.fraTop)
        self.cboEvent.setObjectName("cboEvent")
        self.gridLayout_2.addWidget(self.cboEvent, 3, 2, 1, 1)
        self.lblStatistic = QtWidgets.QLabel(self.fraTop)
        self.lblStatistic.setObjectName("lblStatistic")
        self.gridLayout_2.addWidget(self.lblStatistic, 4, 1, 1, 1)
        self.cboStatistic = QtWidgets.QComboBox(self.fraTop)
        self.cboStatistic.setObjectName("cboStatistic")
        self.gridLayout_2.addWidget(self.cboStatistic, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.fraTop)
        self.gbxThresholds = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxThresholds.setObjectName("gbxThresholds")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxThresholds)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblPrecip = QtWidgets.QLabel(self.gbxThresholds)
        self.lblPrecip.setObjectName("lblPrecip")
        self.gridLayout.addWidget(self.lblPrecip, 0, 0, 1, 1)
        self.lblVolume = QtWidgets.QLabel(self.gbxThresholds)
        self.lblVolume.setObjectName("lblVolume")
        self.gridLayout.addWidget(self.lblVolume, 3, 0, 1, 1)
        self.txtMinEventValue = QtWidgets.QLineEdit(self.gbxThresholds)
        self.txtMinEventValue.setObjectName("txtMinEventValue")
        self.gridLayout.addWidget(self.txtMinEventValue, 0, 1, 1, 1)
        self.txtMinEventVolume = QtWidgets.QLineEdit(self.gbxThresholds)
        self.txtMinEventVolume.setObjectName("txtMinEventVolume")
        self.gridLayout.addWidget(self.txtMinEventVolume, 3, 1, 1, 1)
        self.txtMinEventDelta = QtWidgets.QLineEdit(self.gbxThresholds)
        self.txtMinEventDelta.setObjectName("txtMinEventDelta")
        self.gridLayout.addWidget(self.txtMinEventDelta, 4, 1, 1, 1)
        self.lblSeparation = QtWidgets.QLabel(self.gbxThresholds)
        self.lblSeparation.setObjectName("lblSeparation")
        self.gridLayout.addWidget(self.lblSeparation, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbxThresholds)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fraMid = QtWidgets.QFrame(self.fraOKCancel)
        self.fraMid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMid.setObjectName("fraMid")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraMid)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addWidget(self.fraMid)
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmStatisticsReportSelection.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmStatisticsReportSelection)
        QtCore.QMetaObject.connectSlotsByName(frmStatisticsReportSelection)

    def retranslateUi(self, frmStatisticsReportSelection):
        _translate = QtCore.QCoreApplication.translate
        frmStatisticsReportSelection.setWindowTitle(_translate("frmStatisticsReportSelection", "SWMM Statistics Report Selection"))
        self.lblCategory.setText(_translate("frmStatisticsReportSelection", "Object Category"))
        self.lblName.setText(_translate("frmStatisticsReportSelection", "Object Name"))
        self.lblVariable.setText(_translate("frmStatisticsReportSelection", "Variable Analyzed"))
        self.lblEvent.setText(_translate("frmStatisticsReportSelection", "Event Time Period"))
        self.lblStatistic.setText(_translate("frmStatisticsReportSelection", "Statistic"))
        self.gbxThresholds.setTitle(_translate("frmStatisticsReportSelection", "Event Thresholds"))
        self.lblPrecip.setText(_translate("frmStatisticsReportSelection", "Precipitation"))
        self.lblVolume.setText(_translate("frmStatisticsReportSelection", "Event Volume"))
        self.lblSeparation.setText(_translate("frmStatisticsReportSelection", "Separation Time"))
        self.cmdOK.setText(_translate("frmStatisticsReportSelection", "OK"))
        self.cmdCancel.setText(_translate("frmStatisticsReportSelection", "Cancel"))

