# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSummaryReportDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSummaryReport(object):
    def setupUi(self, frmSummaryReport):
        frmSummaryReport.setObjectName("frmSummaryReport")
        frmSummaryReport.resize(541, 385)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmSummaryReport.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmSummaryReport)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraTop)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraTopic = QtWidgets.QFrame(self.fraTop)
        self.fraTopic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTopic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTopic.setObjectName("fraTopic")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraTopic)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblTopic = QtWidgets.QLabel(self.fraTopic)
        self.lblTopic.setObjectName("lblTopic")
        self.horizontalLayout_2.addWidget(self.lblTopic)
        self.cboType = QtWidgets.QComboBox(self.fraTopic)
        self.cboType.setObjectName("cboType")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.cboType.addItem("")
        self.horizontalLayout_2.addWidget(self.cboType)
        self.label = QtWidgets.QLabel(self.fraTopic)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fraTopic)
        self.tblSummary = QtWidgets.QTableWidget(self.fraTop)
        self.tblSummary.setObjectName("tblSummary")
        self.tblSummary.setColumnCount(0)
        self.tblSummary.setRowCount(0)
        self.verticalLayout.addWidget(self.tblSummary)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmSummaryReport.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmSummaryReport)
        QtCore.QMetaObject.connectSlotsByName(frmSummaryReport)

    def retranslateUi(self, frmSummaryReport):
        _translate = QtCore.QCoreApplication.translate
        frmSummaryReport.setWindowTitle(_translate("frmSummaryReport", "SWMM Summary Report"))
        self.lblTopic.setText(_translate("frmSummaryReport", "Topic:"))
        self.cboType.setItemText(0, _translate("frmSummaryReport", "Subcatchment Runoff"))
        self.cboType.setItemText(1, _translate("frmSummaryReport", "Subcatchment Washoff"))
        self.cboType.setItemText(2, _translate("frmSummaryReport", "Node Depth"))
        self.cboType.setItemText(3, _translate("frmSummaryReport", "Node Inflow"))
        self.cboType.setItemText(4, _translate("frmSummaryReport", "Node Surcharge"))
        self.cboType.setItemText(5, _translate("frmSummaryReport", "Node Flooding"))
        self.cboType.setItemText(6, _translate("frmSummaryReport", "Outfall Loading"))
        self.cboType.setItemText(7, _translate("frmSummaryReport", "Link Flow"))
        self.cboType.setItemText(8, _translate("frmSummaryReport", "Conduit Surcharge"))
        self.cboType.setItemText(9, _translate("frmSummaryReport", "Link Pollutant Load"))
        self.label.setText(_translate("frmSummaryReport", "Click a column header to sort the column."))
        self.cmdCancel.setText(_translate("frmSummaryReport", "Close"))

