# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTimeseriesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTimeseries(object):
    def setupUi(self, frmTimeseries):
        frmTimeseries.setObjectName("frmTimeseries")
        frmTimeseries.resize(648, 456)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTimeseries.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmTimeseries)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.gridLayout = QtWidgets.QGridLayout(self.fraParms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTimeseriesName = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblTimeseriesName.setFont(font)
        self.lblTimeseriesName.setObjectName("lblTimeseriesName")
        self.gridLayout.addWidget(self.lblTimeseriesName, 0, 0, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.fraParms)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.txtTimeseriesName = QtWidgets.QLineEdit(self.fraParms)
        self.txtTimeseriesName.setObjectName("txtTimeseriesName")
        self.gridLayout.addWidget(self.txtTimeseriesName, 0, 1, 1, 1)
        self.txtDescription = QtWidgets.QLineEdit(self.fraParms)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.fraParms)
        self.fraMid = QtWidgets.QFrame(self.centralWidget)
        self.fraMid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMid.setObjectName("fraMid")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fraMid)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtExternalFile = QtWidgets.QLineEdit(self.fraMid)
        self.txtExternalFile.setObjectName("txtExternalFile")
        self.gridLayout_3.addWidget(self.txtExternalFile, 2, 0, 1, 1)
        self.btnFile = QtWidgets.QToolButton(self.fraMid)
        self.btnFile.setObjectName("btnFile")
        self.gridLayout_3.addWidget(self.btnFile, 2, 3, 1, 1)
        self.rbnExternal = QtWidgets.QRadioButton(self.fraMid)
        self.rbnExternal.setObjectName("rbnExternal")
        self.gridLayout_3.addWidget(self.rbnExternal, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 5, 3, 1, 1)
        self.btnView = QtWidgets.QPushButton(self.fraMid)
        self.btnView.setObjectName("btnView")
        self.gridLayout_3.addWidget(self.btnView, 5, 4, 1, 1)
        self.lblNote = QtWidgets.QLabel(self.fraMid)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblNote.setFont(font)
        self.lblNote.setObjectName("lblNote")
        self.gridLayout_3.addWidget(self.lblNote, 5, 0, 1, 1)
        self.rbnTable = QtWidgets.QRadioButton(self.fraMid)
        self.rbnTable.setObjectName("rbnTable")
        self.gridLayout_3.addWidget(self.rbnTable, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.fraMid)
        self.fraBottom = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraBottom.sizePolicy().hasHeightForWidth())
        self.fraBottom.setSizePolicy(sizePolicy)
        self.fraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBottom.setObjectName("fraBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraBottom)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fraLeft = QtWidgets.QFrame(self.fraBottom)
        self.fraLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraLeft.setObjectName("fraLeft")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fraLeft)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblTime = QtWidgets.QTableWidget(self.fraLeft)
        self.tblTime.setRowCount(24)
        self.tblTime.setColumnCount(3)
        self.tblTime.setObjectName("tblTime")
        item = QtWidgets.QTableWidgetItem()
        self.tblTime.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(2, item)
        self.tblTime.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tblTime)
        self.horizontalLayout_2.addWidget(self.fraLeft)
        self.fraRight = QtWidgets.QFrame(self.fraBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraRight.sizePolicy().hasHeightForWidth())
        self.fraRight.setSizePolicy(sizePolicy)
        self.fraRight.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fraRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRight.setObjectName("fraRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraRight)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.fraOKCancel = QtWidgets.QFrame(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraOKCancel.sizePolicy().hasHeightForWidth())
        self.fraOKCancel.setSizePolicy(sizePolicy)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        self.horizontalLayout_2.addWidget(self.fraRight)
        self.verticalLayout_2.addWidget(self.fraBottom)
        frmTimeseries.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTimeseries)
        QtCore.QMetaObject.connectSlotsByName(frmTimeseries)

    def retranslateUi(self, frmTimeseries):
        _translate = QtCore.QCoreApplication.translate
        frmTimeseries.setWindowTitle(_translate("frmTimeseries", "SWMM Time Series Editor"))
        self.lblTimeseriesName.setText(_translate("frmTimeseries", "Time Series Name"))
        self.lblDescription.setText(_translate("frmTimeseries", "<html><head/><body><p>Description</p></body></html>"))
        self.btnFile.setText(_translate("frmTimeseries", "..."))
        self.rbnExternal.setText(_translate("frmTimeseries", "Use external data file named below"))
        self.btnView.setText(_translate("frmTimeseries", "View"))
        self.lblNote.setText(_translate("frmTimeseries", "No dates means times are relative to start of simulation."))
        self.rbnTable.setText(_translate("frmTimeseries", "Enter time series data in the table below"))
        item = self.tblTime.verticalHeaderItem(0)
        item.setText(_translate("frmTimeseries", "1"))
        item = self.tblTime.horizontalHeaderItem(0)
        item.setText(_translate("frmTimeseries", "Date (M/D/Y)"))
        item = self.tblTime.horizontalHeaderItem(1)
        item.setText(_translate("frmTimeseries", "Time (H:M)"))
        item = self.tblTime.horizontalHeaderItem(2)
        item.setText(_translate("frmTimeseries", "Value"))
        self.cmdOK.setText(_translate("frmTimeseries", "OK"))
        self.cmdCancel.setText(_translate("frmTimeseries", "Cancel"))

