# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTimeSeriesPlotDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTimeSeriesPlot(object):
    def setupUi(self, frmTimeSeriesPlot):
        frmTimeSeriesPlot.setObjectName("frmTimeSeriesPlot")
        frmTimeSeriesPlot.resize(381, 478)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTimeSeriesPlot.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmTimeSeriesPlot)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxTimePeriods = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxTimePeriods.setObjectName("gbxTimePeriods")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxTimePeriods)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblStart = QtWidgets.QLabel(self.gbxTimePeriods)
        self.lblStart.setObjectName("lblStart")
        self.gridLayout.addWidget(self.lblStart, 0, 0, 1, 1)
        self.cboStart = QtWidgets.QComboBox(self.gbxTimePeriods)
        self.cboStart.setObjectName("cboStart")
        self.gridLayout.addWidget(self.cboStart, 1, 0, 1, 1)
        self.lblEnd = QtWidgets.QLabel(self.gbxTimePeriods)
        self.lblEnd.setObjectName("lblEnd")
        self.gridLayout.addWidget(self.lblEnd, 0, 1, 1, 1)
        self.cboEnd = QtWidgets.QComboBox(self.gbxTimePeriods)
        self.cboEnd.setObjectName("cboEnd")
        self.gridLayout.addWidget(self.cboEnd, 1, 1, 1, 1)
        self.rbnElapsed = QtWidgets.QRadioButton(self.gbxTimePeriods)
        self.rbnElapsed.setObjectName("rbnElapsed")
        self.gridLayout.addWidget(self.rbnElapsed, 2, 0, 1, 1)
        self.rbnDate = QtWidgets.QRadioButton(self.gbxTimePeriods)
        self.rbnDate.setObjectName("rbnDate")
        self.gridLayout.addWidget(self.rbnDate, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbxTimePeriods)
        self.gbxData = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxData.setObjectName("gbxData")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxData)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraButtons = QtWidgets.QFrame(self.gbxData)
        self.fraButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraButtons.setObjectName("fraButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraButtons)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QToolButton(self.fraButtons)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QToolButton(self.fraButtons)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout_2.addWidget(self.btnRemove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnLoad = QtWidgets.QToolButton(self.fraButtons)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_2.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QToolButton(self.fraButtons)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnScript = QtWidgets.QToolButton(self.fraButtons)
        self.btnScript.setObjectName("btnScript")
        self.horizontalLayout_2.addWidget(self.btnScript)
        self.verticalLayout_2.addWidget(self.fraButtons)
        self.lstData = QtWidgets.QListWidget(self.gbxData)
        self.lstData.setObjectName("lstData")
        self.verticalLayout_2.addWidget(self.lstData)
        self.verticalLayout.addWidget(self.gbxData)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmTimeSeriesPlot.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTimeSeriesPlot)
        QtCore.QMetaObject.connectSlotsByName(frmTimeSeriesPlot)

    def retranslateUi(self, frmTimeSeriesPlot):
        _translate = QtCore.QCoreApplication.translate
        frmTimeSeriesPlot.setWindowTitle(_translate("frmTimeSeriesPlot", "SWMM Time Series Plot Selection"))
        self.gbxTimePeriods.setTitle(_translate("frmTimeSeriesPlot", "Time Periods"))
        self.lblStart.setText(_translate("frmTimeSeriesPlot", "Start Date"))
        self.lblEnd.setText(_translate("frmTimeSeriesPlot", "End Date"))
        self.rbnElapsed.setText(_translate("frmTimeSeriesPlot", "Elapsed Time"))
        self.rbnDate.setText(_translate("frmTimeSeriesPlot", "Date/Time"))
        self.gbxData.setTitle(_translate("frmTimeSeriesPlot", "Data Series"))
        self.btnAdd.setText(_translate("frmTimeSeriesPlot", "+"))
        self.btnRemove.setText(_translate("frmTimeSeriesPlot", "-"))
        self.btnLoad.setText(_translate("frmTimeSeriesPlot", "Load"))
        self.btnSave.setText(_translate("frmTimeSeriesPlot", "Save"))
        self.btnScript.setText(_translate("frmTimeSeriesPlot", "To Script"))
        self.cmdOK.setText(_translate("frmTimeSeriesPlot", "OK"))
        self.cmdCancel.setText(_translate("frmTimeSeriesPlot", "Cancel"))

