# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTransectDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTransect(object):
    def setupUi(self, frmTransect):
        frmTransect.setObjectName("frmTransect")
        frmTransect.resize(546, 503)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTransect.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmTransect)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraTop)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblDescription = QtWidgets.QLabel(self.fraTop)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout_2.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.fraTop)
        self.txtName.setObjectName("txtName")
        self.gridLayout_2.addWidget(self.txtName, 0, 2, 1, 1)
        self.lblGroup = QtWidgets.QLabel(self.fraTop)
        self.lblGroup.setObjectName("lblGroup")
        self.gridLayout_2.addWidget(self.lblGroup, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.txtDescription = QtWidgets.QLineEdit(self.fraTop)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout_2.addWidget(self.txtDescription, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.fraTop)
        self.fraMiddle = QtWidgets.QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMiddle.setObjectName("fraMiddle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraMiddle)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblTransect = QtWidgets.QTableWidget(self.fraMiddle)
        self.tblTransect.setRowCount(100)
        self.tblTransect.setObjectName("tblTransect")
        self.tblTransect.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tblTransect.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTransect.setHorizontalHeaderItem(1, item)
        self.tblTransect.horizontalHeader().setCascadingSectionResizes(False)
        self.tblTransect.horizontalHeader().setDefaultSectionSize(100)
        self.tblTransect.horizontalHeader().setStretchLastSection(True)
        self.tblTransect.verticalHeader().setDefaultSectionSize(30)
        self.tblTransect.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tblTransect)
        self.gbxProperties = QtWidgets.QGroupBox(self.fraMiddle)
        self.gbxProperties.setObjectName("gbxProperties")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxProperties)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblElevations = QtWidgets.QLabel(self.gbxProperties)
        self.lblElevations.setObjectName("lblElevations")
        self.gridLayout.addWidget(self.lblElevations, 9, 0, 1, 1)
        self.lblStations = QtWidgets.QLabel(self.gbxProperties)
        self.lblStations.setObjectName("lblStations")
        self.gridLayout.addWidget(self.lblStations, 8, 0, 1, 1)
        self.txtLeftSta = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtLeftSta.setObjectName("txtLeftSta")
        self.gridLayout.addWidget(self.txtLeftSta, 5, 1, 1, 1)
        self.txtRightSta = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtRightSta.setObjectName("txtRightSta")
        self.gridLayout.addWidget(self.txtRightSta, 6, 1, 1, 1)
        self.lblRight = QtWidgets.QLabel(self.gbxProperties)
        self.lblRight.setObjectName("lblRight")
        self.gridLayout.addWidget(self.lblRight, 6, 0, 1, 1)
        self.lblLeft = QtWidgets.QLabel(self.gbxProperties)
        self.lblLeft.setObjectName("lblLeft")
        self.gridLayout.addWidget(self.lblLeft, 5, 0, 1, 1)
        self.lblBankStations = QtWidgets.QLabel(self.gbxProperties)
        self.lblBankStations.setObjectName("lblBankStations")
        self.gridLayout.addWidget(self.lblBankStations, 4, 0, 1, 1)
        self.lblModifiers = QtWidgets.QLabel(self.gbxProperties)
        self.lblModifiers.setObjectName("lblModifiers")
        self.gridLayout.addWidget(self.lblModifiers, 7, 0, 1, 1)
        self.lblMeander = QtWidgets.QLabel(self.gbxProperties)
        self.lblMeander.setObjectName("lblMeander")
        self.gridLayout.addWidget(self.lblMeander, 10, 0, 1, 1)
        self.txtStations = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtStations.setObjectName("txtStations")
        self.gridLayout.addWidget(self.txtStations, 8, 1, 1, 1)
        self.txtRightBank = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtRightBank.setObjectName("txtRightBank")
        self.gridLayout.addWidget(self.txtRightBank, 2, 1, 1, 1)
        self.lblRightBank = QtWidgets.QLabel(self.gbxProperties)
        self.lblRightBank.setObjectName("lblRightBank")
        self.gridLayout.addWidget(self.lblRightBank, 2, 0, 1, 1)
        self.lblLeftBank = QtWidgets.QLabel(self.gbxProperties)
        self.lblLeftBank.setObjectName("lblLeftBank")
        self.gridLayout.addWidget(self.lblLeftBank, 1, 0, 1, 1)
        self.txtLeftBank = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtLeftBank.setObjectName("txtLeftBank")
        self.gridLayout.addWidget(self.txtLeftBank, 1, 1, 1, 1)
        self.lblRough = QtWidgets.QLabel(self.gbxProperties)
        self.lblRough.setObjectName("lblRough")
        self.gridLayout.addWidget(self.lblRough, 0, 0, 1, 1)
        self.txtChannel = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtChannel.setObjectName("txtChannel")
        self.gridLayout.addWidget(self.txtChannel, 3, 1, 1, 1)
        self.lblChannel = QtWidgets.QLabel(self.gbxProperties)
        self.lblChannel.setObjectName("lblChannel")
        self.gridLayout.addWidget(self.lblChannel, 3, 0, 1, 1)
        self.txtElevations = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtElevations.setObjectName("txtElevations")
        self.gridLayout.addWidget(self.txtElevations, 9, 1, 1, 1)
        self.txtMeander = QtWidgets.QLineEdit(self.gbxProperties)
        self.txtMeander.setObjectName("txtMeander")
        self.gridLayout.addWidget(self.txtMeander, 10, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbxProperties)
        self.verticalLayout.addWidget(self.fraMiddle)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnView = QtWidgets.QPushButton(self.fraOKCancel)
        self.btnView.setObjectName("btnView")
        self.horizontalLayout.addWidget(self.btnView)
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmTransect.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTransect)
        QtCore.QMetaObject.connectSlotsByName(frmTransect)

    def retranslateUi(self, frmTransect):
        _translate = QtCore.QCoreApplication.translate
        frmTransect.setWindowTitle(_translate("frmTransect", "SWMM Transect Editor"))
        self.lblDescription.setText(_translate("frmTransect", "Description"))
        self.lblGroup.setText(_translate("frmTransect", "Transect Name"))
        item = self.tblTransect.horizontalHeaderItem(0)
        item.setText(_translate("frmTransect", "Station (ft)"))
        item = self.tblTransect.horizontalHeaderItem(1)
        item.setText(_translate("frmTransect", "Elevation (ft)"))
        self.gbxProperties.setTitle(_translate("frmTransect", "Properties"))
        self.lblElevations.setText(_translate("frmTransect", "  Elevations"))
        self.lblStations.setText(_translate("frmTransect", "  Stations"))
        self.lblRight.setText(_translate("frmTransect", "  Right"))
        self.lblLeft.setText(_translate("frmTransect", "  Left"))
        self.lblBankStations.setText(_translate("frmTransect", "Bank Stations:"))
        self.lblModifiers.setText(_translate("frmTransect", "Modifiers:"))
        self.lblMeander.setText(_translate("frmTransect", "  Meander"))
        self.lblRightBank.setText(_translate("frmTransect", "  Right Bank"))
        self.lblLeftBank.setText(_translate("frmTransect", "  Left Bank"))
        self.lblRough.setText(_translate("frmTransect", "Roughness:"))
        self.lblChannel.setText(_translate("frmTransect", "  Channel"))
        self.btnView.setText(_translate("frmTransect", "View..."))
        self.cmdOK.setText(_translate("frmTransect", "OK"))
        self.cmdCancel.setText(_translate("frmTransect", "Cancel"))

