# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTableSelectionDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTableSelection(object):
    def setupUi(self, frmTableSelection):
        frmTableSelection.setObjectName("frmTableSelection")
        frmTableSelection.resize(416, 333)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTableSelection.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmTableSelection)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.gridLayout = QtWidgets.QGridLayout(self.fraTop)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.cboObject = QtWidgets.QComboBox(self.fraTop)
        self.cboObject.setObjectName("cboObject")
        self.gridLayout.addWidget(self.cboObject, 3, 1, 1, 1)
        self.lblTime = QtWidgets.QLabel(self.fraTop)
        self.lblTime.setObjectName("lblTime")
        self.gridLayout.addWidget(self.lblTime, 2, 0, 1, 1)
        self.lblObject = QtWidgets.QLabel(self.fraTop)
        self.lblObject.setObjectName("lblObject")
        self.gridLayout.addWidget(self.lblObject, 2, 1, 1, 1)
        self.cboTime = QtWidgets.QComboBox(self.fraTop)
        self.cboTime.setObjectName("cboTime")
        self.gridLayout.addWidget(self.cboTime, 3, 0, 1, 1)
        self.lblVariables = QtWidgets.QLabel(self.fraTop)
        self.lblVariables.setObjectName("lblVariables")
        self.gridLayout.addWidget(self.lblVariables, 4, 0, 1, 1)
        self.lblNodes = QtWidgets.QLabel(self.fraTop)
        self.lblNodes.setObjectName("lblNodes")
        self.gridLayout.addWidget(self.lblNodes, 4, 1, 1, 1)
        self.cboEnd = QtWidgets.QComboBox(self.fraTop)
        self.cboEnd.setObjectName("cboEnd")
        self.gridLayout.addWidget(self.cboEnd, 1, 1, 1, 1)
        self.lblEnd = QtWidgets.QLabel(self.fraTop)
        self.lblEnd.setObjectName("lblEnd")
        self.gridLayout.addWidget(self.lblEnd, 0, 1, 1, 1)
        self.cboStart = QtWidgets.QComboBox(self.fraTop)
        self.cboStart.setObjectName("cboStart")
        self.gridLayout.addWidget(self.cboStart, 1, 0, 1, 1)
        self.lblStart = QtWidgets.QLabel(self.fraTop)
        self.lblStart.setObjectName("lblStart")
        self.gridLayout.addWidget(self.lblStart, 0, 0, 1, 1)
        self.lstNodes = QtWidgets.QListWidget(self.fraTop)
        self.lstNodes.setObjectName("lstNodes")
        self.gridLayout.addWidget(self.lstNodes, 5, 1, 1, 1)
        self.lstVariables = QtWidgets.QListWidget(self.fraTop)
        self.lstVariables.setObjectName("lstVariables")
        self.gridLayout.addWidget(self.lstVariables, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmTableSelection.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTableSelection)
        QtCore.QMetaObject.connectSlotsByName(frmTableSelection)

    def retranslateUi(self, frmTableSelection):
        _translate = QtCore.QCoreApplication.translate
        frmTableSelection.setWindowTitle(_translate("frmTableSelection", "SWMM Table Selection"))
        self.lblTime.setText(_translate("frmTableSelection", "Time Format"))
        self.lblObject.setText(_translate("frmTableSelection", "Object Category"))
        self.lblVariables.setText(_translate("frmTableSelection", "Variables"))
        self.lblNodes.setText(_translate("frmTableSelection", "Nodes"))
        self.lblEnd.setText(_translate("frmTableSelection", "End Date"))
        self.lblStart.setText(_translate("frmTableSelection", "Start Date"))
        self.cmdOK.setText(_translate("frmTableSelection", "OK"))
        self.cmdCancel.setText(_translate("frmTableSelection", "Cancel"))

