# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmUnitHydrographDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmUnitHydrograph(object):
    def setupUi(self, frmUnitHydrograph):
        frmUnitHydrograph.setObjectName("frmUnitHydrograph")
        frmUnitHydrograph.resize(460, 543)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmUnitHydrograph.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmUnitHydrograph)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraTop)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblGroup = QtWidgets.QLabel(self.fraTop)
        self.lblGroup.setObjectName("lblGroup")
        self.gridLayout_2.addWidget(self.lblGroup, 0, 0, 1, 1)
        self.txtGroup = QtWidgets.QLineEdit(self.fraTop)
        self.txtGroup.setObjectName("txtGroup")
        self.gridLayout_2.addWidget(self.txtGroup, 0, 1, 1, 1)
        self.lblRain = QtWidgets.QLabel(self.fraTop)
        self.lblRain.setObjectName("lblRain")
        self.gridLayout_2.addWidget(self.lblRain, 1, 0, 1, 1)
        self.cboRain = QtWidgets.QComboBox(self.fraTop)
        self.cboRain.setObjectName("cboRain")
        self.gridLayout_2.addWidget(self.cboRain, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.fraTop)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.fraUpperMiddle = QtWidgets.QFrame(self.centralWidget)
        self.fraUpperMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraUpperMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraUpperMiddle.setObjectName("fraUpperMiddle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraUpperMiddle)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblHydrograph = QtWidgets.QLabel(self.fraUpperMiddle)
        self.lblHydrograph.setObjectName("lblHydrograph")
        self.horizontalLayout_2.addWidget(self.lblHydrograph)
        self.cboHydrograph = QtWidgets.QComboBox(self.fraUpperMiddle)
        self.cboHydrograph.setObjectName("cboHydrograph")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.cboHydrograph.addItem("")
        self.horizontalLayout_2.addWidget(self.cboHydrograph)
        self.verticalLayout_6.addWidget(self.fraUpperMiddle)
        self.fraMiddle = QtWidgets.QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMiddle.setObjectName("fraMiddle")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fraMiddle)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabHydrograph = QtWidgets.QTabWidget(self.fraMiddle)
        self.tabHydrograph.setObjectName("tabHydrograph")
        self.tabUnit = QtWidgets.QWidget()
        self.tabUnit.setObjectName("tabUnit")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabUnit)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblPack = QtWidgets.QTableWidget(self.tabUnit)
        self.tblPack.setRowCount(3)
        self.tblPack.setObjectName("tblPack")
        self.tblPack.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(2, item)
        self.tblPack.horizontalHeader().setCascadingSectionResizes(False)
        self.tblPack.horizontalHeader().setDefaultSectionSize(100)
        self.tblPack.horizontalHeader().setStretchLastSection(True)
        self.tblPack.verticalHeader().setDefaultSectionSize(30)
        self.tblPack.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tblPack)
        self.fraNote1 = QtWidgets.QFrame(self.tabUnit)
        self.fraNote1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNote1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNote1.setObjectName("fraNote1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraNote1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNote1 = QtWidgets.QLabel(self.fraNote1)
        self.lblNote1.setObjectName("lblNote1")
        self.verticalLayout.addWidget(self.lblNote1)
        self.lblNote2 = QtWidgets.QLabel(self.fraNote1)
        self.lblNote2.setObjectName("lblNote2")
        self.verticalLayout.addWidget(self.lblNote2)
        self.lblNote3 = QtWidgets.QLabel(self.fraNote1)
        self.lblNote3.setObjectName("lblNote3")
        self.verticalLayout.addWidget(self.lblNote3)
        self.verticalLayout_4.addWidget(self.fraNote1)
        self.tabHydrograph.addTab(self.tabUnit, "")
        self.tabAbstraction = QtWidgets.QWidget()
        self.tabAbstraction.setObjectName("tabAbstraction")
        self.gridLayout = QtWidgets.QGridLayout(self.tabAbstraction)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.fraNote2 = QtWidgets.QFrame(self.tabAbstraction)
        self.fraNote2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraNote2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraNote2.setObjectName("fraNote2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraNote2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblNote4 = QtWidgets.QLabel(self.fraNote2)
        self.lblNote4.setObjectName("lblNote4")
        self.verticalLayout_2.addWidget(self.lblNote4)
        self.lblNote5 = QtWidgets.QLabel(self.fraNote2)
        self.lblNote5.setObjectName("lblNote5")
        self.verticalLayout_2.addWidget(self.lblNote5)
        self.lblNote6 = QtWidgets.QLabel(self.fraNote2)
        self.lblNote6.setObjectName("lblNote6")
        self.verticalLayout_2.addWidget(self.lblNote6)
        self.gridLayout.addWidget(self.fraNote2, 1, 0, 1, 1)
        self.tblAbstraction = QtWidgets.QTableWidget(self.tabAbstraction)
        self.tblAbstraction.setRowCount(3)
        self.tblAbstraction.setObjectName("tblAbstraction")
        self.tblAbstraction.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(2, item)
        self.tblAbstraction.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAbstraction.horizontalHeader().setDefaultSectionSize(100)
        self.tblAbstraction.horizontalHeader().setStretchLastSection(True)
        self.tblAbstraction.verticalHeader().setDefaultSectionSize(30)
        self.tblAbstraction.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAbstraction, 0, 0, 1, 1)
        self.tabHydrograph.addTab(self.tabAbstraction, "")
        self.verticalLayout_5.addWidget(self.tabHydrograph)
        self.lblGeneral = QtWidgets.QLabel(self.fraMiddle)
        self.lblGeneral.setObjectName("lblGeneral")
        self.verticalLayout_5.addWidget(self.lblGeneral)
        self.verticalLayout_6.addWidget(self.fraMiddle)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_6.addWidget(self.fraOKCancel)
        frmUnitHydrograph.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmUnitHydrograph)
        self.tabHydrograph.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmUnitHydrograph)

    def retranslateUi(self, frmUnitHydrograph):
        _translate = QtCore.QCoreApplication.translate
        frmUnitHydrograph.setWindowTitle(_translate("frmUnitHydrograph", "SWMM Unit Hydrograph Editor"))
        self.lblGroup.setText(_translate("frmUnitHydrograph", "Name of UH Group"))
        self.lblRain.setText(_translate("frmUnitHydrograph", "Rain Gage Used"))
        self.lblHydrograph.setText(_translate("frmUnitHydrograph", "Hydrographs For:"))
        self.cboHydrograph.setItemText(0, _translate("frmUnitHydrograph", "All Months"))
        self.cboHydrograph.setItemText(1, _translate("frmUnitHydrograph", "January"))
        self.cboHydrograph.setItemText(2, _translate("frmUnitHydrograph", "February"))
        self.cboHydrograph.setItemText(3, _translate("frmUnitHydrograph", "March"))
        self.cboHydrograph.setItemText(4, _translate("frmUnitHydrograph", "April"))
        self.cboHydrograph.setItemText(5, _translate("frmUnitHydrograph", "May"))
        self.cboHydrograph.setItemText(6, _translate("frmUnitHydrograph", "June"))
        self.cboHydrograph.setItemText(7, _translate("frmUnitHydrograph", "July"))
        self.cboHydrograph.setItemText(8, _translate("frmUnitHydrograph", "August"))
        self.cboHydrograph.setItemText(9, _translate("frmUnitHydrograph", "September"))
        self.cboHydrograph.setItemText(10, _translate("frmUnitHydrograph", "October"))
        self.cboHydrograph.setItemText(11, _translate("frmUnitHydrograph", "November"))
        self.cboHydrograph.setItemText(12, _translate("frmUnitHydrograph", "December"))
        item = self.tblPack.verticalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Short-Term"))
        item = self.tblPack.verticalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Medium-Term"))
        item = self.tblPack.verticalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Long-Term"))
        item = self.tblPack.horizontalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "R"))
        item = self.tblPack.horizontalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "T"))
        item = self.tblPack.horizontalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "K"))
        self.lblNote1.setText(_translate("frmUnitHydrograph", "R = fraction of rainfall that becomes I&I"))
        self.lblNote2.setText(_translate("frmUnitHydrograph", "T = time to hydrograph peak (hours)"))
        self.lblNote3.setText(_translate("frmUnitHydrograph", "K = falling limb duration / rising limb duration"))
        self.tabHydrograph.setTabText(self.tabHydrograph.indexOf(self.tabUnit), _translate("frmUnitHydrograph", "Unit Hydrographs"))
        self.lblNote4.setText(_translate("frmUnitHydrograph", "Dmax = maximum depth (inches)"))
        self.lblNote5.setText(_translate("frmUnitHydrograph", "Drec = recovery rate (in/day)"))
        self.lblNote6.setText(_translate("frmUnitHydrograph", "Do = starting depth (inches)"))
        item = self.tblAbstraction.verticalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Short-Term"))
        item = self.tblAbstraction.verticalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Medium-Term"))
        item = self.tblAbstraction.verticalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Long-Term"))
        item = self.tblAbstraction.horizontalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Dmax"))
        item = self.tblAbstraction.horizontalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Drec"))
        item = self.tblAbstraction.horizontalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Do"))
        self.tabHydrograph.setTabText(self.tabHydrograph.indexOf(self.tabAbstraction), _translate("frmUnitHydrograph", "Initial Abstraction Depth"))
        self.lblGeneral.setText(_translate("frmUnitHydrograph", "Months with UH data have a (*) next to them."))
        self.cmdOK.setText(_translate("frmUnitHydrograph", "OK"))
        self.cmdCancel.setText(_translate("frmUnitHydrograph", "Cancel"))

